import type { Sql, TransactionSql } from 'postgres';
import { InventoryConstants } from '../../src/common/inventoryConstants';
import { findFreeSlot, type Footprint } from '../../src/common/inventoryFit';
import { JEWEL_OF_CHAOS } from '../../src/common/jewelUpgrade';
import { productById, type Product } from './catalog';
import {
  audit,
  claimForDelivery,
  clearLock,
  deliveringOrders,
  explainDelivering,
  journalLock,
  LOCK_STALE_MS,
  type Order,
  type QueuedOrder,
  queuedOrders,
  settle,
  staleLocks,
} from './db';
import { describeRoll, type Roll } from './gacha';
import {
  type AccountRow,
  type GateVerdict,
  quote,
  type ResolvedSchema,
  type ResolvedTable,
  type SafetyGate,
  type SignalResult,
} from './gate';

/**
 * Delivery: the worker that drains the order queue, and the one transaction
 * in this repository that writes to OpenMU's database.
 *
 * Everything the gate exists for is at stake here. OpenMU keeps a logged-in
 * account in a private EF Core context and writes it back on save, so a row
 * written under a live session is either duped (the jewels this deletes were
 * already spent in game, unsaved) or clobbered (the slot this fills is filled
 * again by the next save). The worker therefore never writes on its own
 * judgement: `SafetyGate.check` has to say safe first, the account is locked
 * out of login for the length of the write, and the write itself is one
 * short transaction ordered so that every refusal costs the player nothing.
 * The steps are ARCHITECTURE.md's "The fulfilment transaction", with Jewels
 * of Chaos in place of Bless and Soul.
 *
 * Two things this file will not do. It does not re-roll: a gacha order arrives
 * with the roll that was committed when it was paid for, and what is granted
 * is that roll, seed and all. And it does not guess a column name: OpenMU's
 * tables are generated by EF Core, so every identifier below comes from
 * `gate.ts`'s resolver, which lists the write side's tables beside the ones
 * it reads, and a database that does not look as expected is refused at boot
 * before any statement touches it.
 *
 * `CASHSHOP_FULFIL` is off unless it says `on`. Off runs the gate, the wallet
 * read and the fit exactly as a delivery would, logs the rows it would delete
 * and insert, and then rolls the transaction back. That is the mode to run
 * against a new database until its output has been read.
 */

/* ------------------------------------------------------------------ config */

export interface FulfilmentConfig {
  /** Whether anything is ever written. Off is a rehearsal with the real gate and reads. */
  fulfil: boolean;
  /** How often the queue is looked at. Every look costs a gate check per account with orders. */
  pollMs: number;
  /** How often locks left behind by a dead process are restored. */
  sweepMs: number;
}

export function loadFulfilmentConfig(
  env: Record<string, string | undefined> = process.env
): FulfilmentConfig {
  return {
    fulfil: env.CASHSHOP_FULFIL === 'on',
    pollMs: Number(env.CASHSHOP_POLL_MS ?? 15_000),
    sweepMs: Number(env.CASHSHOP_SWEEP_MS ?? LOCK_STALE_MS),
  };
}

/**
 * `AccountState` (`DataModel/Entities/AccountState.cs`): the only state the
 * lock may start from and the one it sets. `LoginAction.ValidateAccountStateAsync`
 * refuses `TemporarilyBanned` at login, which is what closes the window between
 * "presence says offline" and COMMIT. Nothing else is ever written to `State`,
 * so the shop can never unban anyone.
 */
const ACCOUNT_NORMAL = 0;
const ACCOUNT_TEMPORARILY_BANNED = 5;

/**
 * Which jewels go first. Bag before vault: the bag is where the item is about
 * to land, so spending from it first is what makes room for the delivery, and
 * the vault holds what the player chose to put away.
 */
const SPEND_ORDER: readonly ('inventory' | 'vault')[] = ['inventory', 'vault'];

/**
 * What a rehearsed order is told. Whether deliveries are switched on is the
 * operator's setting, not the player's business, and the order really is
 * waiting: the words say that and nothing else. What the rehearsal found -
 * the bag, the slot, the jewels it would take - goes to the audit row and the
 * log, where the operator reads.
 */
const REHEARSAL_WORDS = 'Deliveries are paused for now. Your order keeps its place.';

/**
 * The excellent option a label in `Roll.options` stands for, as OpenMU numbers
 * them. `ExcellentOptions.cs` in the Season 6 initialisation creates the
 * defensive set as `IncreasableItemOption.Number` 1 to 6 in this order - zen,
 * defence rate, reflect, damage decrease, mana, life - and the item serializer
 * puts option n on wire bit n-1, which is the order the client's tooltip reads
 * them back in. Matched on a word rather than the whole label so the reveal's
 * wording can be tuned without a delivery silently granting the wrong bonus;
 * a label that matches no line, or more than one, refuses the order.
 */
const EXCELLENT_NUMBERS: readonly [pattern: RegExp, number: number][] = [
  [/zen/i, 1],
  [/defen/i, 2],
  [/reflect/i, 3],
  [/decrease/i, 4],
  [/mana/i, 5],
  [/life/i, 6],
];

/** How `ItemOptionTypes.Excellent` is named in `config."ItemOptionType"`, best first. */
const EXCELLENT_TYPE_NAMES = ['Excellent Option', 'Excellent'];

/**
 * `ItemOptionLink.Level` is 1 for an option whose value does not grow, which
 * is every excellent option; `Index` is for socketed options only.
 */
const OPTION_LINK_LEVEL = 1;
const OPTION_LINK_INDEX = 0;

/* ------------------------------------------------------------------- schema */

/**
 * A column this INSERT does not supply and the database will not default is
 * a row OpenMU could not have written, so the shape is checked once, up
 * front, against exactly the columns the statement names.
 */
function assertInsertable(table: ResolvedTable, written: string[]): void {
  const supplied = new Set(written.map(column => column.replace(/^"|"$/g, '')));
  const unknown = [...table.required].filter(column => !supplied.has(column));

  if (unknown.length) {
    throw new Error(
      `${table.ref} requires ${unknown.map(quote).join(', ')}, ` +
        'which this shop does not know how to fill'
    );
  }
}

/* ------------------------------------------------------------ definitions */

interface DefinitionRow {
  id: string;
  name: string;
  width: number;
  height: number;
  durability: number;
  maximumLevel: number;
}

/**
 * What the transaction has resolved once and reuses: the configuration every
 * definition lookup is scoped to, the id of the excellent option type, and
 * the Jewel of Chaos's own definition.
 */
interface Resolved {
  schema: ResolvedSchema;
  gameConfigurationId: string;
  excellentTypeId: string;
  chaosDefinitionId: string;
}

/**
 * `config."ItemDefinition"` rows belong to a `GameConfiguration`. With one in
 * the database there is nothing to choose; with several, the one the game
 * server runs is the one every `GameServerDefinition` points at, and if they
 * disagree nobody can say which configuration a player is in, so the shop
 * refuses rather than grant an item from a configuration nobody plays.
 */
async function resolveGameConfiguration(sql: Sql, schema: ResolvedSchema): Promise<string> {
  const { gameConfiguration: g, gameServerDefinition: s } = schema;
  const configurations = await sql.unsafe<{ id: string }[]>(
    `SELECT ${g.col.id} AS id FROM ${g.ref}`
  );

  if (configurations.length === 0) {
    throw new Error('no GameConfiguration in the database, so no item definition can be granted');
  }

  if (configurations.length === 1) return configurations[0].id;

  const used = await sql.unsafe<{ id: string }[]>(
    `SELECT DISTINCT ${s.col.configuration} AS id FROM ${s.ref}`
  );
  const ids = used.map(row => row.id).filter((id): id is string => id !== null);

  if (ids.length !== 1) {
    throw new Error(
      `${configurations.length} GameConfigurations exist and the game servers point at ` +
        `${ids.length === 0 ? 'none of them' : `${ids.length} different ones`}, ` +
        'so the one being played cannot be identified'
    );
  }

  return ids[0];
}

async function resolveExcellentType(sql: Sql, schema: ResolvedSchema): Promise<string> {
  const { itemOptionType: t } = schema;
  const rows = await sql.unsafe<{ id: string; name: string }[]>(
    `SELECT ${t.col.id} AS id, ${t.col.name} AS name FROM ${t.ref}`
  );

  for (const wanted of EXCELLENT_TYPE_NAMES) {
    const exact = rows.filter(row => row.name === wanted);
    if (exact.length === 1) return exact[0].id;
  }

  const prefixed = rows.filter(row => /^excellent/i.test(row.name));

  if (prefixed.length === 1) return prefixed[0].id;

  throw new Error(
    'cannot tell which ItemOptionType is the excellent one ' +
      `(looked for ${EXCELLENT_TYPE_NAMES.join(', ')}; ` +
      `the table has ${rows.map(row => row.name).sort().join(', ')})`
  );
}

async function findDefinition(
  sql: Sql | TransactionSql,
  resolved: Resolved,
  group: number,
  number: number
): Promise<DefinitionRow | null> {
  const { itemDefinition: d } = resolved.schema;
  const rows = await sql.unsafe<DefinitionRow[]>(
    `SELECT ${d.col.id} AS id, ${d.col.name} AS name,
            ${d.col.width} AS width, ${d.col.height} AS height,
            ${d.col.durability} AS durability, ${d.col.maximumLevel} AS "maximumLevel"
       FROM ${d.ref}
      WHERE ${d.col.configuration} = $1 AND ${d.col.group} = $2 AND ${d.col.number} = $3
      LIMIT 2`,
    [resolved.gameConfigurationId, group, number]
  );

  if (rows.length > 1) {
    throw new Error(
      `item ${group}/${number} has ${rows.length} definitions in the game configuration`
    );
  }

  return rows[0] ?? null;
}

/**
 * The excellent options a definition can carry, by number, through its own
 * `PossibleItemOptions`. Resolving through the item's definition rather than
 * a hardcoded id is what keeps a granted item legal: an option that does not
 * belong to the item is one OpenMU can load but never produce.
 */
async function excellentOptionsOf(
  sql: Sql | TransactionSql,
  resolved: Resolved,
  definitionId: string
): Promise<Map<number, string>> {
  const { definitionOptions: j, increasableOption: o } = resolved.schema;
  const rows = await sql.unsafe<{ number: number; id: string }[]>(
    `SELECT o.${o.col.number} AS number, o.${o.col.id} AS id
       FROM ${o.ref} o
       JOIN ${j.ref} j ON j.${j.col.optionDefinition} = o.${o.col.optionDefinition}
      WHERE j.${j.col.definition} = $1 AND o.${o.col.type} = $2`,
    [definitionId, resolved.excellentTypeId]
  );

  const byNumber = new Map<number, string>();
  for (const row of rows) byNumber.set(Number(row.number), row.id);
  return byNumber;
}

function excellentNumberOf(label: string): number {
  const hits = EXCELLENT_NUMBERS.filter(([pattern]) => pattern.test(label));

  if (hits.length !== 1) {
    throw new Refusal(
      `The option "${label}" is not one the game knows. Nothing was spent.`,
      'failed'
    );
  }

  return hits[0][1];
}

/* --------------------------------------------------------------------- fit */

interface PlacedRow extends Footprint {
  id: string;
}

/**
 * `InventoryConstants` knows about the four purchasable extensions, four rows
 * each, but the client does not draw them: `PlayerData.items` is 76 entries
 * (`src/store.ts`) and the inventory window is 8x8. An item fitted into an
 * extension row would exist and be invisible, so the fit stops at the base
 * grid until the client can show more. Flip this when it can.
 */
const DELIVER_INTO_EXTENSIONS = false;

/**
 * How many grid rows a delivery may use. The search over them is
 * `findFreeSlot`, the client's own loop, so that the slot chosen here is the
 * slot the client would have chosen; rows the personal store uses (from
 * `FirstStoreItemSlotIndex`) share the storage and lie outside the grid, as
 * do the twelve equipment slots.
 */
function gridRows(inventoryExtensions: number): number {
  const extensions = DELIVER_INTO_EXTENSIONS
    ? Math.max(Math.min(inventoryExtensions, InventoryConstants.MaximumNumberOfExtensions), 0)
    : 0;

  return InventoryConstants.InventoryRows + InventoryConstants.RowsOfOneExtension * extensions;
}

/* ------------------------------------------------------------------ wallet */

interface JewelRow {
  id: string;
  storage: 'inventory' | 'vault';
  slot: number;
}

/**
 * Every Jewel of Chaos the account owns, in the bag and in the vault, in the
 * order they would be spent. `FOR UPDATE` inside the transaction so that two
 * deliveries cannot both count the same jewel; a plain read outside it for
 * the wallet the placement route shows.
 */
async function chaosRows(
  sql: Sql | TransactionSql,
  resolved: Resolved,
  inventoryId: string | null,
  vaultId: string | null,
  lock: boolean
): Promise<JewelRow[]> {
  const { item: i } = resolved.schema;
  const storages: [string, JewelRow['storage']][] = [];

  if (inventoryId) storages.push([inventoryId, 'inventory']);
  if (vaultId) storages.push([vaultId, 'vault']);
  if (storages.length === 0) return [];

  const rows = await sql.unsafe<{ id: string; storage: string; slot: number }[]>(
    `SELECT i.${i.col.id} AS id, i.${i.col.storage} AS storage, i.${i.col.slot} AS slot
       FROM ${i.ref} i
      WHERE i.${i.col.definition} = $1 AND i.${i.col.storage} = ANY($2::uuid[])
      ORDER BY i.${i.col.slot}${lock ? ' FOR UPDATE OF i' : ''}`,
    [resolved.chaosDefinitionId, sql.array(storages.map(([id]) => id))]
  );

  const kindOf = new Map(storages);
  const jewels = rows.map(row => ({
    id: row.id,
    storage: kindOf.get(row.storage) ?? 'vault',
    slot: Number(row.slot),
  }));

  return jewels.sort(
    (a, b) => SPEND_ORDER.indexOf(a.storage) - SPEND_ORDER.indexOf(b.storage) || a.slot - b.slot
  );
}

/* --------------------------------------------------------------- the order */

interface CharacterRow {
  id: string;
  name: string;
  inventoryId: string;
  slot: number;
  inventoryExtensions: number;
}

/** What one delivery resolved before it touched anything, for the audit row. */
interface Grant {
  definitionId: string;
  definitionName: string;
  level: number;
  width: number;
  height: number;
  durability: number;
  /** `IncreasableItemOption` ids, in option-number order. */
  optionIds: string[];
  seed: number | null;
}

interface Delivery {
  character: string;
  slot: number;
  spent: JewelRow[];
  walletBefore: number;
  grant: Grant;
  itemId: string | null;
}

/**
 * A refusal the player will read. `queued` means try again next time - the
 * order keeps its place - and `failed` means the order is over and nothing
 * was spent. Every path through the transaction that is not a commit ends in
 * one of these, in words rather than a stack trace.
 */
class Refusal extends Error {
  constructor(
    message: string,
    readonly outcome: 'queued' | 'failed'
  ) {
    super(message);
  }
}

/**
 * Wraps whatever the transaction callback threw, so the caller can tell
 * "before COMMIT" from "around it".
 */
class BeforeCommit extends Error {
  constructor(readonly inner: unknown) {
    super('before commit');
  }
}

/** Thrown at the end of a rehearsal so the transaction rolls back with its reads done. */
class Rehearsed extends Error {
  constructor(readonly delivery: Delivery) {
    super('rehearsal');
  }
}

/** The order's product, or the grant a fixed product resolves to on the catalogue. */
function productOf(order: Order): Product {
  const product = productById(order.productId);

  if (!product) {
    throw new Refusal(
      `The shop no longer sells "${order.productName}". Nothing was spent.`,
      'failed'
    );
  }

  return product;
}

/**
 * What to insert. A fixed product is its catalogue entry at its level; a
 * gacha order is its stored roll, granted exactly - the seed is in the audit
 * row so the item can be checked against `roll(seed)` later. Both are checked
 * against the game's own definition: the footprint the shop fitted must be the
 * footprint the game will draw, and the level must be one the definition
 * allows.
 */
async function resolveGrant(tx: TransactionSql, resolved: Resolved, order: Order): Promise<Grant> {
  const product = productOf(order);
  let group: number;
  let number: number;
  let level: number;
  let width: number;
  let height: number;
  let labels: string[] = [];
  let seed: number | null = null;

  if (order.line === 'gacha') {
    const roll: Roll | null = order.roll;

    if (!roll) {
      throw new Refusal(
        'This roll was never recorded, so it cannot be delivered. Nothing was spent.',
        'failed'
      );
    }

    ({ group, num: number, level, width, height, seed } = roll);
    labels = roll.excellent ? roll.options : [];
  } else {
    if (product.group === null || product.number === null) {
      throw new Refusal(`"${product.name}" is not an item the shop can place in a bag.`, 'failed');
    }

    ({ group, number, level, width, height } = product);
  }

  const definition = await findDefinition(tx, resolved, group, number);

  if (!definition) {
    throw new Refusal(
      `The game has no item ${group}/${number} to give you. Nothing was spent.`,
      'failed'
    );
  }

  if (definition.width !== width || definition.height !== height) {
    throw new Refusal(
      `The game says "${definition.name}" is ${definition.width}x${definition.height}, ` +
        `the shop thought ${width}x${height}. Nothing was spent.`,
      'failed'
    );
  }

  if (level > definition.maximumLevel) {
    throw new Refusal(
      `"${definition.name}" cannot be +${level}; ` +
        `the game allows up to +${definition.maximumLevel}. Nothing was spent.`,
      'failed'
    );
  }

  const optionIds: string[] = [];

  if (labels.length > 0) {
    const available = await excellentOptionsOf(tx, resolved, definition.id);
    const numbers = [...new Set(labels.map(excellentNumberOf))].sort((a, b) => a - b);

    for (const n of numbers) {
      const id = available.get(n);

      if (!id) {
        throw new Refusal(
          `"${definition.name}" cannot carry excellent option ${n} in this game. ` +
            'Nothing was spent.',
          'failed'
        );
      }

      optionIds.push(id);
    }
  }

  return {
    definitionId: definition.id,
    definitionName: definition.name,
    level,
    width,
    height,
    durability: Number(definition.durability),
    optionIds,
    seed,
  };
}

/**
 * The character whose bag takes a delivery and whose jewels pay for it - the
 * same character for both on purpose, because the fit treats the bag jewels
 * about to be spent as free squares, and that only holds when the spend and
 * the delivery are one bag.
 *
 * ARCHITECTURE.md says "the selected character's inventory", and OpenMU has
 * no such thing to read: `Character` (`DataModel/Entities/Character.cs`)
 * carries `CharacterSlot` and `CreateDate` but no last-played time, `Account`
 * names no current character, and which character a player is on lives in
 * the game server's memory. So the rule is the lowest `CharacterSlot` - the
 * first on the select screen, which the player made first and sees first.
 * `Fulfilment.wallet` counts the same character's bag plus the vault, so the
 * balance the window shows is the balance delivery will spend from. Whatever
 * lands there can be moved through the vault to any other character.
 */
async function deliveryCharacter(
  sql: Sql | TransactionSql,
  resolved: Resolved,
  accountId: string
): Promise<CharacterRow | null> {
  const { character: c } = resolved.schema;
  const rows = await sql.unsafe<CharacterRow[]>(
    `SELECT ${c.col.id} AS id, ${c.col.name} AS name, ${c.col.inventory} AS "inventoryId",
            ${c.col.slot} AS slot, ${c.col.inventoryExtensions} AS "inventoryExtensions"
       FROM ${c.ref}
      WHERE ${c.col.account} = $1 AND ${c.col.inventory} IS NOT NULL
      ORDER BY ${c.col.slot} ASC, ${c.col.id} ASC
      LIMIT 1`,
    [accountId]
  );

  if (!rows[0]) return null;

  return {
    ...rows[0],
    slot: Number(rows[0].slot),
    inventoryExtensions: Number(rows[0].inventoryExtensions),
  };
}

/**
 * Steps 6 to 13. Everything in here runs on the transaction's own connection;
 * a statement on the module-level `sql` would run outside the advisory lock
 * and outside the rollback.
 *
 * The order of the steps is the safety: the wallet is read under lock, the
 * item is resolved and fitted, and only then is anything deleted - so a
 * refusal at any point, including a bag with no room, has cost nothing. The
 * fit treats the bag jewels about to be spent as free squares, since the
 * delete that frees them is in this same transaction; that is what lets a
 * bag full of chaos take the item it is paying for.
 */
async function deliverInTransaction(
  tx: TransactionSql,
  resolved: Resolved,
  account: AccountRow,
  order: Order,
  rehearse: boolean
): Promise<Delivery> {
  const { item: i, itemOptionLink: l, itemDefinition: d } = resolved.schema;

  await tx.unsafe('SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))', [account.id]);

  const character = await deliveryCharacter(tx, resolved, account.id);

  if (!character) {
    throw new Refusal(
      'You have no character to deliver to. Create one and the order will be delivered.',
      'queued'
    );
  }

  const jewels = await chaosRows(tx, resolved, character.inventoryId, account.vaultId, true);

  if (jewels.length < order.chaos) {
    throw new Refusal(
      `You have ${jewels.length} Jewel${jewels.length === 1 ? '' : 's'} of Chaos ` +
        `and this costs ${order.chaos}. Nothing was spent.`,
      'failed'
    );
  }

  const spent = jewels.slice(0, order.chaos);
  const spentIds = new Set(spent.map(jewel => jewel.id));
  const grant = await resolveGrant(tx, resolved, order);

  const placed = await tx.unsafe<PlacedRow[]>(
    `SELECT i.${i.col.id} AS id, i.${i.col.slot} AS slot,
            d.${d.col.width} AS width, d.${d.col.height} AS height
       FROM ${i.ref} i
       JOIN ${d.ref} d ON d.${d.col.id} = i.${i.col.definition}
      WHERE i.${i.col.storage} = $1 AND i.${i.col.slot} >= $2 AND i.${i.col.slot} < $3`,
    [
      character.inventoryId,
      InventoryConstants.LastEquippableItemSlotIndex + 1,
      InventoryConstants.FirstStoreItemSlotIndex,
    ]
  );
  const occupied: Footprint[] = placed
    .filter(row => !spentIds.has(row.id))
    .map(row => ({
      slot: Number(row.slot),
      width: Number(row.width),
      height: Number(row.height),
    }));
  const rows = gridRows(character.inventoryExtensions);
  const slot = findFreeSlot(occupied, rows, grant.width, grant.height);

  if (slot < 0) {
    // The one refusal that is nobody's fault, and for a gacha the one that
    // must not void a roll committed at placement: it waits for the next
    // logout with room in the bag. A fixed product can simply be bought
    // again, so it fails and gives its daily-cap slot back.
    throw new Refusal(
      `No room in ${character.name}'s bag for a ${grant.width}x${grant.height} item. ` +
        `Make ${grant.width * grant.height} squares free and log out again. Nothing was spent.`,
      order.line === 'gacha' ? 'queued' : 'failed'
    );
  }

  const delivery: Delivery = {
    character: character.name,
    slot,
    spent,
    walletBefore: jewels.length,
    grant,
    itemId: null,
  };

  if (rehearse) throw new Rehearsed(delivery);

  const ids = tx.array(spent.map(jewel => jewel.id));

  // Option rows first, then the items: a jewel has none, but a foreign key is
  // not a thing to find out about mid-transaction.
  await tx.unsafe(`DELETE FROM ${l.ref} WHERE ${l.col.item} = ANY($1::uuid[])`, [ids]);
  const deleted = await tx.unsafe(`DELETE FROM ${i.ref} WHERE ${i.col.id} = ANY($1::uuid[])`, [ids]);

  if (deleted.count !== spent.length) {
    throw new Error(`expected to delete ${spent.length} jewels, deleted ${deleted.count}`);
  }

  const itemColumns = [
    i.col.id,
    i.col.storage,
    i.col.definition,
    i.col.slot,
    i.col.durability,
    i.col.level,
    i.col.hasSkill,
    i.col.socketCount,
    i.col.petExperience,
  ];
  assertInsertable(i, itemColumns);

  const inserted = await tx.unsafe<{ id: string }[]>(
    `INSERT INTO ${i.ref} (${itemColumns.join(', ')})
     VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, false, 0, 0)
     RETURNING ${i.col.id} AS id`,
    [character.inventoryId, grant.definitionId, slot, grant.durability, grant.level]
  );
  const itemId = inserted[0]?.id;

  if (!itemId) throw new Error('the item INSERT returned no id');

  if (grant.optionIds.length > 0) {
    const linkColumns = [l.col.id, l.col.item, l.col.option, l.col.level, l.col.index];
    assertInsertable(l, linkColumns);

    for (const optionId of grant.optionIds) {
      await tx.unsafe(
        `INSERT INTO ${l.ref} (${linkColumns.join(', ')})
         VALUES (gen_random_uuid(), $1, $2, $3, $4)`,
        [itemId, optionId, OPTION_LINK_LEVEL, OPTION_LINK_INDEX]
      );
    }
  }

  return { ...delivery, itemId };
}

/* ----------------------------------------------------------------- reasons */

/**
 * The gate's refusal, in the words the delivery tab shows. The signal names
 * and their technical reasons go to the audit log; the player gets told what
 * to do about it.
 */
function playerWords(verdict: GateVerdict): string {
  const refused = verdict.signals.filter(signal => !signal.safe);
  const named = (name: SignalResult['name']) => refused.find(signal => signal.name === name);

  const presence = named('presence');
  if (presence) {
    if (/logged in/.test(presence.reason)) {
      return 'You are logged in. Log out and it will be delivered within a minute.';
    }
    if (/logged out/.test(presence.reason)) {
      return 'You logged out a moment ago. It will be delivered within a minute.';
    }
    return 'The shop cannot see who is online right now. It will keep trying.';
  }

  if (named('writeRecency')) {
    return (
      'Your characters were saved a moment ago, so you may still be playing. ' +
      'It will be delivered once the game has been quiet for a few minutes.'
    );
  }

  if (named('personalStore')) {
    return 'A character on your account has a personal store open. Close it and log out.';
  }

  return 'Deliveries are paused while the server is checked. Your order keeps its place.';
}

function describe(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** The audit's view of a verdict: every signal, safe or not. */
function signalsOf(verdict: GateVerdict): Record<string, { safe: boolean; reason: string }> {
  const out: Record<string, { safe: boolean; reason: string }> = {};
  for (const signal of verdict.signals) out[signal.name] = { safe: signal.safe, reason: signal.reason };
  return out;
}

/* ------------------------------------------------------------------ worker */

/**
 * The delivery worker. One per process, sharing the one `SafetyGate`: the
 * gate's sampling fallback and probe cache live on the instance, and a fresh
 * gate per order would refuse forever on a database without commit
 * timestamps.
 *
 * One account at a time, and all of an account's queued orders in one pass
 * under one gate verdict and one State lock. That is not only faster: the
 * write-recency signal reads `data."Item"`, so the shop's own commit looks
 * like a save for the next three minutes, and delivering twelve gacha rolls
 * one pass apiece would take the better part of an hour.
 */
export class Fulfilment {
  private resolved: Resolved | null = null;
  private timer: ReturnType<typeof setTimeout> | null = null;
  private sweeper: ReturnType<typeof setInterval> | null = null;
  private running = false;
  private stopped = false;
  /** Accounts whose `State` this process holds locked right now, by id, for the sweep. */
  private readonly inFlight = new Set<string>();
  /**
   * `group/number` -> whether the game configuration defines it. Definitions
   * do not change while the server runs.
   */
  private readonly grantableByKey = new Map<string, boolean>();

  constructor(
    private readonly sql: Sql,
    private readonly gate: SafetyGate,
    private readonly config: FulfilmentConfig = loadFulfilmentConfig()
  ) {}

  get mode(): 'on' | 'off' {
    return this.config.fulfil ? 'on' : 'off';
  }

  /** Whether the service can honestly tell the window it will deliver. */
  get acceptingOrders(): boolean {
    return this.resolved !== null;
  }

  /**
   * Resolves the schema and the configuration once, so a database that does
   * not look as expected is refused at boot, loudly, and not on the first
   * order. Retried on every poll until it succeeds, because the database may
   * simply not be up yet. The schema is the gate's own resolution: one walk
   * of `information_schema` per process, and no way for the two to disagree.
   */
  async resolveOnce(): Promise<Resolved> {
    if (this.resolved) return this.resolved;

    const schema = await this.gate.schemaOnce();
    const gameConfigurationId = await resolveGameConfiguration(this.sql, schema);
    const excellentTypeId = await resolveExcellentType(this.sql, schema);
    const partial = { schema, gameConfigurationId, excellentTypeId, chaosDefinitionId: '' };
    const chaos = await findDefinition(this.sql, partial, JEWEL_OF_CHAOS.group, JEWEL_OF_CHAOS.num);

    if (!chaos) {
      throw new Error(
        'the game configuration has no Jewel of Chaos ' +
          `(${JEWEL_OF_CHAOS.group}/${JEWEL_OF_CHAOS.num}) definition`
      );
    }

    this.resolved = { ...partial, chaosDefinitionId: chaos.id };
    console.info(
      `cash shop fulfilment ${this.mode}: schema resolved, ` +
        `game configuration ${gameConfigurationId}, chaos definition ${chaos.id}`
    );

    return this.resolved;
  }

  /**
   * Whether the running game configuration defines this item at all, so a
   * gacha roll can be checked before it is committed rather than failing the
   * player at delivery with an item the game cannot hand over. Null when the
   * database cannot be asked, which the caller must treat as "do not roll".
   */
  async grantable(group: number, number: number): Promise<boolean | null> {
    const key = `${group}/${number}`;
    const known = this.grantableByKey.get(key);

    if (known !== undefined) return known;

    try {
      const resolved = await this.resolveOnce();
      const found = (await findDefinition(this.sql, resolved, group, number)) !== null;

      this.grantableByKey.set(key, found);

      return found;
    } catch (error) {
      console.error(`definition lookup for ${key} failed:`, describe(error));
      return null;
    }
  }

  /**
   * The wallet as the database has it: the delivery character's bag plus the
   * vault (`deliveryCharacter` says why that character and no other), which
   * is the placement route's bound. Null when the account is unknown or the
   * schema is not resolved yet, which the route should treat as "cannot
   * accept orders", never as zero.
   */
  async wallet(loginName: string): Promise<{ chaos: number } | null> {
    try {
      const resolved = await this.resolveOnce();
      const account = await this.gate.findAccount(loginName);

      if (!account) return null;

      const character = await deliveryCharacter(this.sql, resolved, account.id);
      const jewels = await chaosRows(
        this.sql,
        resolved,
        character?.inventoryId ?? null,
        account.vaultId,
        false
      );

      return { chaos: jewels.length };
    } catch (error) {
      console.error(`wallet read for ${loginName} failed:`, error);
      return null;
    }
  }

  start(): void {
    if (this.timer || this.sweeper) return;
    this.stopped = false;

    console.info(
      `cash shop fulfilment is ${this.mode}` +
        (this.config.fulfil
          ? ''
          : ' (rehearsing: nothing will be written; set CASHSHOP_FULFIL=on)')
    );

    this.reportInterrupted();
    void this.sweep();
    this.sweeper = setInterval(() => void this.sweep(), this.config.sweepMs);
    this.sweeper.unref();
    this.schedule(0);
  }

  /**
   * Orders a previous process claimed and never settled. A claim and its
   * settlement happen in one pass, so anything still `delivering` at boot
   * was cut off - by a deploy's restart, most likely - and whether its
   * transaction committed is a fact only OpenMU's database holds. Requeueing
   * would deliver twice if it did; failing would tell the player nothing was
   * spent if it was. So they are named, loudly, and left for a person and
   * `cashshop-orders`.
   */
  private reportInterrupted(): void {
    const interrupted = deliveringOrders();

    if (interrupted.length === 0) return;

    for (const order of interrupted) {
      explainDelivering(order.id, 'Delivery was interrupted. Someone will check it.');
      audit('found delivering at boot', { account: order.account, orderId: order.id });
    }

    console.error(
      `${interrupted.length} order(s) were left delivering by a previous run ` +
        'and need a person to settle them (bun run cashshop-orders): ' +
        interrupted.map(order => `${order.id} for ${order.account}`).join(', ')
    );
  }

  stop(): void {
    this.stopped = true;
    if (this.timer) clearTimeout(this.timer);
    if (this.sweeper) clearInterval(this.sweeper);
    this.timer = null;
    this.sweeper = null;
  }

  private schedule(delay: number): void {
    if (this.stopped) return;
    this.timer = setTimeout(() => void this.tick(), delay);
    this.timer.unref();
  }

  /** One look at the queue. Never overlaps itself: a slow gate check must not stack. */
  async tick(): Promise<void> {
    if (this.running) return;
    this.running = true;

    try {
      const byAccount = new Map<string, QueuedOrder[]>();

      for (const order of queuedOrders()) {
        byAccount.set(order.account, [...(byAccount.get(order.account) ?? []), order]);
      }

      if (byAccount.size > 0) await this.resolveOnce();

      for (const [account, orders] of byAccount) {
        if (this.stopped) break;
        await this.deliverAccount(account, orders);
      }
    } catch (error) {
      console.error('fulfilment pass failed:', describe(error));
    } finally {
      this.running = false;
      this.schedule(this.config.pollMs);
    }
  }

  /**
   * Steps 1 to 5 and 14 to 15 for one account, with every one of its queued
   * orders run through steps 6 to 13 in between, oldest first.
   */
  private async deliverAccount(loginName: string, orders: QueuedOrder[]): Promise<void> {
    const resolved = await this.resolveOnce();
    const first = await this.gate.check(loginName);

    if (!first.safe) {
      this.defer(loginName, orders, first, 'delivery deferred');
      return;
    }

    const account = await this.gate.findAccount(loginName);

    if (!account) {
      const words = 'The shop cannot find your account right now. It will keep trying.';
      for (const order of orders) this.wait(order, words);
      return;
    }

    if (account.state !== ACCOUNT_NORMAL) {
      // A GM, a spectator or a banned account is refused outright: the lock
      // below rewrites State, and the shop must never be able to unban.
      const words = 'Your account is not in a state the shop can deliver to.';
      for (const order of orders) this.wait(order, words);
      audit('delivery refused', {
        account: loginName,
        detail: { state: account.state, orders: orders.map(order => order.id) },
      });
      return;
    }

    const locked = this.config.fulfil ? await this.lock(account) : true;

    if (!locked) {
      const words = 'Your account changed while the shop was checking it. It will try again.';
      for (const order of orders) this.wait(order, words);
      return;
    }

    let pass: { verdict: GateVerdict; committed: number } | null;

    try {
      pass = await this.deliverLocked(resolved, account, loginName, orders);
    } finally {
      if (this.config.fulfil) await this.unlock(account);
    }

    if (!pass) return;

    // Step 15: the same three questions again. The write-recency signal is
    // expected to have flipped - the commits above are writes to this
    // account's items - so it is recorded rather than flagged; presence and
    // the store flag changing is what would mean a session slipped through.
    const after = await this.gate.check(loginName);
    const flipped = after.signals
      .filter(signal => signal.name === 'presence' || signal.name === 'personalStore')
      .filter(signal => !signal.safe);

    audit(flipped.length ? 'post-commit anomaly' : 'post-commit check', {
      account: loginName,
      detail: { committed: pass.committed, before: signalsOf(pass.verdict), after: signalsOf(after) },
    });

    if (flipped.length) {
      console.error(
        `post-commit anomaly for ${loginName}: ` +
          flipped.map(signal => `${signal.name}: ${signal.reason}`).join('; ')
      );
    }
  }

  /**
   * Steps 6 to 13 for each order, behind the reading that counts. The check
   * before the lock bought a cheap refusal and nothing more: its presence
   * answer was taken seconds before `State` changed, and a login whose frame
   * passed the proxy in between is loaded by OpenMU with `State` still
   * Normal, which the lock does not undo. Now that no login can start, every
   * session that did start is one the proxy already knows about, one way or
   * the other: a login OpenMU has answered is named (the proxy names a socket
   * off the server's Okay, and reads it in the same handler that forwards
   * it), and one it has accepted but not yet answered is still a pending
   * claim, which the proxy counts as unidentified and the gate refuses for
   * everyone. So a second reading is authoritative. It fails closed like the
   * first, and the whole pass waits for the next poll.
   */
  private async deliverLocked(
    resolved: Resolved,
    account: AccountRow,
    loginName: string,
    orders: QueuedOrder[]
  ): Promise<{ verdict: GateVerdict; committed: number } | null> {
    const verdict = await this.gate.check(loginName);

    if (!verdict.safe) {
      this.defer(loginName, orders, verdict, 'delivery deferred after lock');
      return null;
    }

    let committed = 0;

    for (const order of orders) {
      if (this.stopped) break;
      if (await this.deliverOrder(resolved, account, order, verdict)) committed++;
    }

    return { verdict, committed };
  }

  /** Every order of the pass told the gate's words, and the whole verdict on one audit row. */
  private defer(loginName: string, orders: QueuedOrder[], verdict: GateVerdict, event: string): void {
    const words = playerWords(verdict);

    for (const order of orders) this.wait(order, words);

    audit(event, {
      account: loginName,
      detail: {
        orders: orders.map(order => order.id),
        refusals: verdict.refusals,
        signals: signalsOf(verdict),
      },
    });
  }

  /**
   * Step 5: journal, then lock. The journal comes first so a crash between
   * the two leaves a record, not a mystery.
   */
  private async lock(account: AccountRow): Promise<boolean> {
    const { account: a } = (await this.resolveOnce()).schema;

    journalLock(account.id, account.state);

    const result = await this.sql.unsafe(
      `UPDATE ${a.ref} SET ${a.col.state} = $1 WHERE ${a.col.id} = $2 AND ${a.col.state} = $3`,
      [ACCOUNT_TEMPORARILY_BANNED, account.id, ACCOUNT_NORMAL]
    );

    if (result.count !== 1) {
      clearLock(account.id);
      return false;
    }

    this.inFlight.add(account.id);

    return true;
  }

  /**
   * Step 14: restore, whatever happened, then clear the journal. Only a row
   * still holding the lock's value is touched.
   */
  private async unlock(account: AccountRow): Promise<void> {
    try {
      const { account: a } = (await this.resolveOnce()).schema;

      await this.sql.unsafe(
        `UPDATE ${a.ref} SET ${a.col.state} = $1 WHERE ${a.col.id} = $2 AND ${a.col.state} = $3`,
        [account.state, account.id, ACCOUNT_TEMPORARILY_BANNED]
      );
      clearLock(account.id);
    } catch (error) {
      // The journal entry stays, and the sweep restores it within the minute.
      console.error(
        `could not restore State for ${account.loginName}; the sweep will:`,
        describe(error)
      );
    } finally {
      this.inFlight.delete(account.id);
    }
  }

  /**
   * One order, claimed and settled. True when a row was committed. The claim
   * is conditional on the order still being queued, so a cancel that landed
   * between the poll and now wins and the order is skipped.
   */
  private async deliverOrder(
    resolved: Resolved,
    account: AccountRow,
    queued: QueuedOrder,
    verdict: GateVerdict
  ): Promise<boolean> {
    const order = claimForDelivery(queued.id);

    if (!order) return false;

    const rehearse = !this.config.fulfil;
    let delivery: Delivery;

    try {
      // Anything thrown by the callback itself is thrown before COMMIT was
      // sent, and Postgres rolls back: nothing was written and the order can
      // safely go back to the queue. Anything that escapes `begin` without
      // that wrapper came from the machinery around the callback - the COMMIT
      // itself, or a connection that dropped after it was sent - and whether
      // the write landed is unknowable from here.
      delivery = await this.sql.begin(async tx => {
        try {
          return await deliverInTransaction(tx, resolved, account, order, rehearse);
        } catch (inner) {
          throw new BeforeCommit(inner);
        }
      });
    } catch (thrown) {
      const error = thrown instanceof BeforeCommit ? thrown.inner : thrown;

      if (!(thrown instanceof BeforeCommit)) {
        // The one outcome this must never turn into a retry: a delivery that
        // did commit would be delivered again, and the jewels taken twice.
        // The order stays `delivering`, the player is told, the audit row
        // carries the error, and `cashshop-orders` is how a person decides.
        explainDelivering(
          order.id,
          'The shop could not tell whether this was delivered. Someone will check it.'
        );
        audit('delivery outcome unknown', {
          account: account.loginName,
          orderId: order.id,
          detail: { error: describe(error), signals: signalsOf(verdict) },
        });
        console.error(
          `order ${order.id} for ${account.loginName}: ` +
            'COMMIT outcome unknown, left as delivering for review:',
          error
        );
        return false;
      }

      if (error instanceof Rehearsed) {
        const { delivery } = error;
        const where = delivery.spent.map(jewel => `${jewel.storage}:${jewel.slot}`).join(', ');

        settle(order.id, 'queued', REHEARSAL_WORDS);
        audit('rehearsed', {
          account: account.loginName,
          orderId: order.id,
          detail: this.auditDetail(order, delivery, verdict),
        });
        console.info(
          `rehearsed order ${order.id} for ${account.loginName}/${delivery.character}: ` +
            `would DELETE ${delivery.spent.length} chaos (${where}) ` +
            `and INSERT ${this.describeGrant(order, delivery)} at slot ${delivery.slot}`
        );
        return false;
      }

      if (error instanceof Refusal) {
        settle(order.id, error.outcome, error.message);
        audit(`delivery ${error.outcome === 'failed' ? 'failed' : 'deferred'}`, {
          account: account.loginName,
          orderId: order.id,
          detail: { reason: error.message, signals: signalsOf(verdict) },
        });
        console.info(`order ${order.id} for ${account.loginName} ${error.outcome}: ${error.message}`);
        return false;
      }

      // Anything else is the database, not the player, and it happened
      // before COMMIT: the order keeps its place, the operator gets the real
      // error, the player gets a sentence.
      settle(order.id, 'queued', 'The shop hit a problem delivering this. It will try again.');
      audit('delivery error', {
        account: account.loginName,
        orderId: order.id,
        detail: { error: describe(error), signals: signalsOf(verdict) },
      });
      console.error(`order ${order.id} for ${account.loginName} errored:`, error);
      return false;
    }

    // Committed. From here on nothing may send the order back to the queue:
    // the item is in the bag and the jewels are gone. A bookkeeping failure
    // leaves it `delivering`, which the boot check and the CLI surface, and
    // is the right side to err on.
    try {
      settle(order.id, 'delivered', `Delivered to ${delivery.character}'s bag.`, delivery.itemId);
      audit('delivered', {
        account: account.loginName,
        orderId: order.id,
        detail: this.auditDetail(order, delivery, verdict),
      });
      console.info(
        `delivered order ${order.id} to ${account.loginName}/${delivery.character}: ` +
          `${this.describeGrant(order, delivery)} at slot ${delivery.slot} ` +
          `for ${delivery.spent.length} chaos`
      );
    } catch (error) {
      console.error(
        `order ${order.id} for ${account.loginName} was delivered (item ${delivery.itemId}) ` +
          'but could not be recorded; it stays delivering for review:',
        error
      );
    }

    return true;
  }

  private describeGrant(order: Order, delivery: Delivery): string {
    const { grant } = delivery;
    const options = grant.optionIds.length ? ` with ${grant.optionIds.length} excellent option(s)` : '';
    const roll = order.roll ? ` [${describeRoll(order.roll)}]` : '';

    return `${grant.definitionName} +${grant.level} (${grant.width}x${grant.height})${options}${roll}`;
  }

  /**
   * Everything ARCHITECTURE.md asks an audit row to name: account, character,
   * product, jewels, item, seed, gate readings.
   */
  private auditDetail(order: Order, delivery: Delivery, verdict: GateVerdict): Record<string, unknown> {
    return {
      productId: order.productId,
      productName: order.productName,
      line: order.line,
      character: delivery.character,
      slot: delivery.slot,
      chaos: order.chaos,
      walletBefore: delivery.walletBefore,
      spent: delivery.spent.map(jewel => ({ id: jewel.id, storage: jewel.storage, slot: jewel.slot })),
      itemId: delivery.itemId,
      definitionId: delivery.grant.definitionId,
      definitionName: delivery.grant.definitionName,
      level: delivery.grant.level,
      optionIds: delivery.grant.optionIds,
      seed: delivery.grant.seed,
      roll: order.roll,
      signals: signalsOf(verdict),
    };
  }

  /**
   * A queued order told why it is waiting. Claimed and handed straight back so
   * the reason lands on the row; only when the reason changed, because every
   * settle is an audit row and a player who stays online is polled all night.
   */
  private wait(order: QueuedOrder, reason: string): void {
    if (order.reason === reason) return;
    if (claimForDelivery(order.id)) settle(order.id, 'queued', reason);
  }

  /**
   * Restores `State` on any account a dead process left locked. Runs at boot
   * and every `sweepMs`, so a SIGKILL mid-transaction costs a player about a
   * minute of "temporarily blocked" and never a permanent lockout. Only a row
   * still holding the lock's value is touched: an operator who changed the
   * state meanwhile is not overruled.
   *
   * A lock this process holds is left alone whatever its age. The journal
   * row's age cannot tell a dead holder from a slow one: a pass delivers all
   * of an account's orders under one lock, and twelve gacha rolls behind a
   * stalled Postgres can honestly outlive `LOCK_STALE_MS`. Restoring `State`
   * under such a pass would reopen login for the rest of it - the very race
   * the lock exists to close - so `inFlight` is consulted first. A process
   * that died has no set to consult, which is the case the sweep is for.
   */
  async sweep(): Promise<void> {
    const stale = staleLocks().filter(lock => !this.inFlight.has(lock.accountId));

    if (stale.length === 0) return;

    let schema: ResolvedSchema;

    try {
      schema = (await this.resolveOnce()).schema;
    } catch (error) {
      console.error(`${stale.length} stale account lock(s) cannot be restored yet:`, describe(error));
      return;
    }

    const { account: a } = schema;

    for (const lock of stale) {
      const age = Math.round((Date.now() - lock.lockedAt) / 1000);

      try {
        const result = await this.sql.unsafe(
          `UPDATE ${a.ref} SET ${a.col.state} = $1 WHERE ${a.col.id} = $2 AND ${a.col.state} = $3`,
          [lock.originalState, lock.accountId, ACCOUNT_TEMPORARILY_BANNED]
        );
        clearLock(lock.accountId);
        audit('stale lock restored', {
          detail: { accountId: lock.accountId, lockedAt: lock.lockedAt, restored: result.count === 1 },
        });
        console.warn(
          `restored State on account ${lock.accountId} locked ${age}s ago` +
            (result.count === 1 ? '' : ' (it was no longer locked)')
        );
      } catch (error) {
        console.error(`could not restore State on account ${lock.accountId}:`, describe(error));
      }
    }
  }
}
