import type { Sql } from 'postgres';

/**
 * The safety gate: may the shop write to this account right now?
 *
 * OpenMU holds a logged-in account in a private EF Core context and writes it
 * back on save, so its database is never the live state. Writing to an account
 * the game server has in memory either dupes the jewels the write spends (they
 * were already spent in game, unsaved) or corrupts an inventory slot the player
 * meanwhile filled.
 *
 * Nothing in the database says who is playing - `LoginServer.cs` is a plain
 * in-memory dictionary - so the gate asks four independent questions and lets
 * any one of them refuse. They are chosen to cover each other's blind spots:
 *
 *   presence      sockets, including a player sitting at character select
 *                 (who is never periodically saved). Blind to offline players
 *                 and to anyone bypassing the proxy.
 *   writeRecency  anything in-world, because `PeriodicSaveProgressPlugIn`
 *                 saves every in-world player once a minute. This is what
 *                 catches OpenMU's offline levelling, which has no socket at
 *                 all. Blind to a live account that changes nothing.
 *   personalStore a character parked with a store open - the idle-but-live
 *                 case the other two miss.
 *   portProbe     whether the game port is reachable from outside. Presence is
 *                 only authoritative while the proxy is the only way in, so
 *                 that gets verified rather than assumed.
 *
 * Every signal fails closed. An error, a timeout, an unreachable service and a
 * missing configuration all read as "refuse", never as "safe".
 */

export type SignalName = 'presence' | 'writeRecency' | 'personalStore' | 'portProbe';

export interface SignalResult {
  name: SignalName;
  safe: boolean;
  /** Always populated, including when safe, so the audit log records what was seen. */
  reason: string;
  detail?: Record<string, unknown>;
}

export interface GateVerdict {
  account: string;
  safe: boolean;
  /** Why not. Empty when safe. */
  refusals: string[];
  signals: SignalResult[];
  checkedAt: number;
}

export interface GateConfig {
  presenceUrl: string;
  /** How long after the last socket closed before a write is allowed. */
  offlineCooldownMs: number;
  /** `PeriodicSaveProgressPlugIn`'s interval. Its default is one minute. */
  saveIntervalMs: number;
  /** Margin on top of two save intervals before recent writes stop counting. */
  recencyMarginMs: number;
  /** The public address of the game server, as a player's .exe would dial it. */
  gameHost: string | null;
  gamePort: number | null;
  probeTimeoutMs: number;
  probeCacheMs: number;
  requestTimeoutMs: number;
}

export function loadGateConfig(env: Record<string, string | undefined> = process.env): GateConfig {
  const port = Number(env.GAME_PROBE_PORT ?? 0);

  return {
    presenceUrl: env.PRESENCE_URL ?? 'http://127.0.0.1:3001',
    offlineCooldownMs: Number(env.OFFLINE_COOLDOWN_MS ?? 60_000),
    saveIntervalMs: Number(env.SAVE_INTERVAL_MS ?? 60_000),
    recencyMarginMs: Number(env.RECENCY_MARGIN_MS ?? 60_000),
    gameHost: env.GAME_PROBE_HOST ?? null,
    gamePort: port > 0 && port <= 65535 ? port : null,
    probeTimeoutMs: Number(env.GAME_PROBE_TIMEOUT_MS ?? 3_000),
    probeCacheMs: Number(env.GAME_PROBE_CACHE_MS ?? 60_000),
    requestTimeoutMs: Number(env.GATE_REQUEST_TIMEOUT_MS ?? 5_000),
  };
}

/* ------------------------------------------------------------------- schema */

/**
 * OpenMU's tables are generated by EF Core, so the column names are convention
 * rather than something this repo can read off a model. Two are confirmed
 * (`Item."DefinitionId"` in `Item.Generated.cs`, `Account."VaultId"` by the
 * register service's INSERT); the rest follow the same `<Navigation>Id` rule.
 *
 * Rather than hardcode the guess, the gate resolves them from
 * `information_schema` on first use and says exactly what is missing when the
 * database disagrees - which is far easier to act on than a syntax error deep
 * inside a query.
 */
interface TableSpec {
  schema: string;
  table: string;
  /** logical name -> the column names that would satisfy it, best first. */
  columns: Record<string, string[]>;
}

const TABLES: Record<'account' | 'character' | 'item', TableSpec> = {
  account: {
    schema: 'data',
    table: 'Account',
    columns: {
      id: ['Id'],
      loginName: ['LoginName'],
      state: ['State'],
      vault: ['VaultId'],
    },
  },
  character: {
    schema: 'data',
    table: 'Character',
    columns: {
      id: ['Id'],
      name: ['Name'],
      account: ['AccountId'],
      inventory: ['InventoryId'],
      storeOpened: ['IsStoreOpened'],
      inventoryExtensions: ['InventoryExtensions'],
    },
  },
  item: {
    schema: 'data',
    table: 'Item',
    columns: {
      id: ['Id'],
      storage: ['ItemStorageId'],
      definition: ['DefinitionId'],
      slot: ['ItemSlot'],
    },
  },
};

export type ResolvedSchema = {
  [K in keyof typeof TABLES]: { schema: string; table: string; columns: Record<string, string> };
};

/** Identifiers are interpolated into SQL, so nothing exotic may pass. */
const IDENTIFIER_RE = /^[A-Za-z][A-Za-z0-9_]*$/;

function quote(name: string): string {
  if (!IDENTIFIER_RE.test(name)) {
    throw new Error(`refusing to use "${name}" as a SQL identifier`);
  }
  return `"${name}"`;
}

export async function resolveSchema(sql: Sql): Promise<ResolvedSchema> {
  const wanted = Object.values(TABLES);
  const rows = await sql<{ table_schema: string; table_name: string; column_name: string }[]>`
    SELECT table_schema, table_name, column_name
    FROM information_schema.columns
    WHERE (table_schema, table_name) IN ${sql(
      wanted.map(spec => [spec.schema, spec.table] as [string, string])
    )}
  `;

  const present = new Map<string, Set<string>>();
  for (const row of rows) {
    const key = `${row.table_schema}.${row.table_name}`;
    let set = present.get(key);
    if (!set) present.set(key, (set = new Set()));
    set.add(row.column_name);
  }

  const resolved = {} as ResolvedSchema;
  const missing: string[] = [];

  for (const [logicalTable, spec] of Object.entries(TABLES)) {
    const key = `${spec.schema}.${spec.table}`;
    const columns = present.get(key);

    if (!columns || columns.size === 0) {
      missing.push(`table ${key} not found`);
      continue;
    }

    const picked: Record<string, string> = {};

    for (const [logicalColumn, candidates] of Object.entries(spec.columns)) {
      const found = candidates.find(candidate => columns.has(candidate));

      if (found) {
        picked[logicalColumn] = found;
      } else {
        missing.push(
          `${key} has no column for ${logicalColumn} (looked for ${candidates.join(', ')}; ` +
            `it has ${[...columns].sort().join(', ')})`
        );
      }
    }

    resolved[logicalTable as keyof ResolvedSchema] = {
      schema: spec.schema,
      table: spec.table,
      columns: picked,
    };
  }

  if (missing.length) {
    throw new Error(`OpenMU schema does not look as expected:\n  ${missing.join('\n  ')}`);
  }

  return resolved;
}

/* -------------------------------------------------------------------- gate */

export interface AccountRow {
  id: string;
  loginName: string;
  state: number;
  vaultId: string | null;
}

interface PresenceAnswer {
  online: boolean;
  connections: number;
  lastSeenAt: number | null;
  startedAt: number;
  now: number;
  unidentifiedConnections: number;
}

interface RecencySample {
  fingerprint: string;
  takenAt: number;
}

export class SafetyGate {
  private schema: ResolvedSchema | null = null;
  private probe: { at: number; open: boolean; detail: string } | null = null;
  /** Only used when `track_commit_timestamp` is off. account id -> last sample. */
  private readonly samples = new Map<string, RecencySample>();
  private commitTimestamps: boolean | null = null;

  constructor(
    private readonly sql: Sql,
    private readonly config: GateConfig = loadGateConfig()
  ) {}

  /** How long a write must be absent before it stops meaning "someone is playing". */
  private get recencyWindowMs(): number {
    return this.config.saveIntervalMs * 2 + this.config.recencyMarginMs;
  }

  async schemaOnce(): Promise<ResolvedSchema> {
    return (this.schema ??= await resolveSchema(this.sql));
  }

  async findAccount(loginName: string): Promise<AccountRow | null> {
    const a = (await this.schemaOnce()).account;
    const rows = await this.sql.unsafe<AccountRow[]>(
      `SELECT ${quote(a.columns.id)} AS id,
              ${quote(a.columns.loginName)} AS "loginName",
              ${quote(a.columns.state)} AS state,
              ${quote(a.columns.vault)} AS "vaultId"
         FROM ${quote(a.schema)}.${quote(a.table)}
        WHERE lower(${quote(a.columns.loginName)}) = lower($1)
        LIMIT 1`,
      [loginName]
    );

    return rows[0] ?? null;
  }

  /**
   * The verdict for one account. Signals run together - three of the four are
   * independent - and every one of them is reported, safe or not, so the audit
   * log can record the whole picture rather than the first refusal.
   */
  async check(loginName: string): Promise<GateVerdict> {
    const checkedAt = Date.now();

    let account: AccountRow | null = null;
    let lookupError: string | null = null;

    try {
      account = await this.findAccount(loginName);
    } catch (error) {
      lookupError = describe(error);
    }

    const dbSignals: Promise<SignalResult[]> =
      lookupError !== null
        ? Promise.resolve([
            refuse('writeRecency', `account lookup failed: ${lookupError}`),
            refuse('personalStore', `account lookup failed: ${lookupError}`),
          ])
        : account === null
          ? Promise.resolve([
              refuse('writeRecency', `no account named ${loginName}`),
              refuse('personalStore', `no account named ${loginName}`),
            ])
          : Promise.all([this.writeRecency(account), this.personalStore(account)]);

    const [presence, [writeRecency, personalStore], portProbe] = await Promise.all([
      this.presence(loginName),
      dbSignals,
      this.portProbe(),
    ]);

    const signals = [presence, writeRecency, personalStore, portProbe];
    const refusals = signals.filter(signal => !signal.safe).map(signal => `${signal.name}: ${signal.reason}`);

    return { account: loginName, safe: refusals.length === 0, refusals, signals, checkedAt };
  }

  /* ---------------------------------------------------------- signal: sockets */

  private async presence(loginName: string): Promise<SignalResult> {
    let answer: PresenceAnswer;

    try {
      const response = await fetch(
        `${this.config.presenceUrl}/presence/${encodeURIComponent(loginName)}`,
        { signal: AbortSignal.timeout(this.config.requestTimeoutMs) }
      );

      if (!response.ok) {
        return refuse('presence', `presence service answered HTTP ${response.status}`);
      }

      answer = (await response.json()) as PresenceAnswer;
    } catch (error) {
      // The proxy being down does not mean nobody is playing - it means we
      // cannot tell, and the whole point of the gate is not to guess.
      return refuse('presence', `presence service unreachable: ${describe(error)}`);
    }

    const detail = {
      connections: answer.connections,
      lastSeenAt: answer.lastSeenAt,
      unidentifiedConnections: answer.unidentifiedConnections,
    };

    if (answer.unidentifiedConnections > 0) {
      return refuse(
        'presence',
        `${answer.unidentifiedConnections} open socket(s) could not be identified, so any of them could be this account`,
        detail
      );
    }

    if (answer.online) {
      return refuse('presence', `logged in on ${answer.connections} connection(s)`, detail);
    }

    // A session this proxy never witnessed died with the previous process, and
    // the game server needs a moment to notice and finish saving - so its
    // start counts as a sighting for the length of the cooldown.
    const since = Math.max(answer.lastSeenAt ?? 0, answer.startedAt);
    const quiet = answer.now - since;

    if (quiet < this.config.offlineCooldownMs) {
      return refuse(
        'presence',
        `logged out ${Math.round(quiet / 1000)}s ago, waiting ${Math.round(this.config.offlineCooldownMs / 1000)}s`,
        detail
      );
    }

    return allow('presence', `no socket for ${Math.round(quiet / 1000)}s`, detail);
  }

  /* ----------------------------------------------------- signal: write recency */

  private async writeRecency(account: AccountRow): Promise<SignalResult> {
    try {
      if (this.commitTimestamps === null) {
        const [row] = await this.sql<{ setting: string }[]>`SHOW track_commit_timestamp`;
        this.commitTimestamps = row?.setting === 'on';
      }

      return this.commitTimestamps
        ? await this.recencyByCommitTimestamp(account)
        : await this.recencyBySampling(account);
    } catch (error) {
      return refuse('writeRecency', `could not read write recency: ${describe(error)}`);
    }
  }

  /** The direct answer, when Postgres is keeping commit timestamps. */
  private async recencyByCommitTimestamp(account: AccountRow): Promise<SignalResult> {
    const rows = await this.sql.unsafe<{ last_write: Date | null }[]>(
      `SELECT max(pg_xact_commit_timestamp(t.xmin)) AS last_write FROM (${this.rowsOfAccountSql()}) t`,
      [account.id]
    );

    const lastWrite = rows[0]?.last_write ?? null;

    if (lastWrite === null) {
      return allow('writeRecency', 'no character or item rows to have been written');
    }

    const age = Date.now() - lastWrite.getTime();
    const detail = { lastWrite: lastWrite.toISOString(), ageMs: age, windowMs: this.recencyWindowMs };

    return age < this.recencyWindowMs
      ? refuse(
          'writeRecency',
          `written ${Math.round(age / 1000)}s ago, which is inside the ${Math.round(this.recencyWindowMs / 1000)}s window`,
          detail
        )
      : allow('writeRecency', `last written ${Math.round(age / 1000)}s ago`, detail);
  }

  /**
   * The fallback when `track_commit_timestamp` is off: compare the rows'
   * transaction ids across two samples more than one save interval apart. An
   * in-world player is saved every minute, so anything that changed between
   * the samples is being played.
   *
   * The first call can only ever answer "not yet" - it has nothing to compare
   * against. That is the cost of not enabling the setting.
   */
  private async recencyBySampling(account: AccountRow): Promise<SignalResult> {
    const rows = await this.sql.unsafe<{ fingerprint: string | null }[]>(
      `SELECT md5(string_agg(t.xmin::text, ',' ORDER BY t.xmin::text)) AS fingerprint
         FROM (${this.rowsOfAccountSql()}) t`,
      [account.id]
    );

    const fingerprint = rows[0]?.fingerprint ?? 'empty';
    const now = Date.now();
    const previous = this.samples.get(account.id);
    const needed = this.config.saveIntervalMs + this.config.recencyMarginMs;

    if (!previous) {
      this.samples.set(account.id, { fingerprint, takenAt: now });
      return refuse(
        'writeRecency',
        `track_commit_timestamp is off, so this needs a second sample in ${Math.round(needed / 1000)}s`,
        { fingerprint, sampled: 1 }
      );
    }

    if (previous.fingerprint !== fingerprint) {
      this.samples.set(account.id, { fingerprint, takenAt: now });
      return refuse('writeRecency', 'rows changed since the last sample, so someone is playing', {
        fingerprint,
        sampled: 2,
      });
    }

    const held = now - previous.takenAt;

    if (held < needed) {
      return refuse(
        'writeRecency',
        `unchanged for only ${Math.round(held / 1000)}s, need ${Math.round(needed / 1000)}s`,
        { fingerprint, heldMs: held }
      );
    }

    return allow('writeRecency', `unchanged for ${Math.round(held / 1000)}s`, {
      fingerprint,
      heldMs: held,
    });
  }

  /**
   * Every character row of the account, plus every item in those characters'
   * inventories and in the account vault. `$1` is the account id.
   */
  private rowsOfAccountSql(): string {
    if (!this.schema) throw new Error('schema not resolved');

    const { account, character, item } = this.schema;
    const characters = `${quote(character.schema)}.${quote(character.table)}`;
    const accounts = `${quote(account.schema)}.${quote(account.table)}`;
    const items = `${quote(item.schema)}.${quote(item.table)}`;

    return `
      SELECT c.xmin FROM ${characters} c WHERE c.${quote(character.columns.account)} = $1
      UNION ALL
      SELECT i.xmin FROM ${items} i
       WHERE i.${quote(item.columns.storage)} IN (
         SELECT c2.${quote(character.columns.inventory)} FROM ${characters} c2
          WHERE c2.${quote(character.columns.account)} = $1
          UNION ALL
         SELECT a.${quote(account.columns.vault)} FROM ${accounts} a
          WHERE a.${quote(account.columns.id)} = $1
       )`;
  }

  /* ---------------------------------------------------- signal: personal store */

  private async personalStore(account: AccountRow): Promise<SignalResult> {
    try {
      const { character } = await this.schemaOnce();
      const rows = await this.sql.unsafe<{ name: string }[]>(
        `SELECT ${quote(character.columns.name)} AS name
           FROM ${quote(character.schema)}.${quote(character.table)}
          WHERE ${quote(character.columns.account)} = $1
            AND ${quote(character.columns.storeOpened)} = true`,
        [account.id]
      );

      return rows.length
        ? refuse('personalStore', `store open on ${rows.map(row => row.name).join(', ')}`, {
            characters: rows.map(row => row.name),
          })
        : allow('personalStore', 'no character has a store open');
    } catch (error) {
      return refuse('personalStore', `could not read store flags: ${describe(error)}`);
    }
  }

  /* --------------------------------------------------------- signal: port probe */

  /**
   * Socket presence is only worth anything while the proxy is the only way in.
   * If the game port answers from its public address, a player on the original
   * client can play without the proxy ever seeing them - so the shop stops
   * writing entirely rather than trusting a signal it knows is bypassable.
   */
  private async portProbe(): Promise<SignalResult> {
    const { gameHost, gamePort } = this.config;

    if (!gameHost || !gamePort) {
      return refuse(
        'portProbe',
        'GAME_PROBE_HOST / GAME_PROBE_PORT are not set, so the proxy cannot be shown to be the only way in'
      );
    }

    const target = `${gameHost}:${gamePort}`;
    const now = Date.now();

    if (this.probe && now - this.probe.at < this.config.probeCacheMs) {
      return this.probe.open
        ? refuse('portProbe', `${target} is reachable (cached): ${this.probe.detail}`)
        : allow('portProbe', `${target} is not reachable (cached): ${this.probe.detail}`);
    }

    const result = await tcpProbe(gameHost, gamePort, this.config.probeTimeoutMs);
    this.probe = { at: now, open: result.open, detail: result.detail };

    return result.open
      ? refuse('portProbe', `${target} is reachable from outside: ${result.detail}`, { target })
      : allow('portProbe', `${target} refused the connection: ${result.detail}`, { target });
  }
}

/* ------------------------------------------------------------------ helpers */

function allow(name: SignalName, reason: string, detail?: Record<string, unknown>): SignalResult {
  return { name, safe: true, reason, detail };
}

function refuse(name: SignalName, reason: string, detail?: Record<string, unknown>): SignalResult {
  return { name, safe: false, reason, detail };
}

function describe(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** Opens a TCP connection and closes it again. Connecting at all is the answer. */
export function tcpProbe(
  host: string,
  port: number,
  timeoutMs: number
): Promise<{ open: boolean; detail: string }> {
  return new Promise(resolve => {
    let settled = false;

    const finish = (open: boolean, detail: string) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({ open, detail });
    };

    const timer = setTimeout(() => finish(false, `no answer in ${timeoutMs}ms`), timeoutMs);

    Bun.connect({
      hostname: host,
      port,
      socket: {
        open(socket) {
          socket.end();
          finish(true, 'connected');
        },
        data() {},
        close() {},
        error(_socket, error) {
          finish(false, describe(error));
        },
        connectError(_socket, error) {
          finish(false, describe(error));
        },
      },
    }).catch(error => finish(false, describe(error)));
  });
}
