import net from 'node:net';
import type { Sql } from 'postgres';

/**
 * The safety gate: may the shop write to this account right now?
 *
 * OpenMU holds a logged-in account in a private EF Core context and writes it
 * back on save, so its database is never the live state. Writing to an account
 * the game server has in memory either dupes the jewels the write spends (they
 * were already spent in game, unsaved) or corrupts an inventory slot the player
 * meanwhile filled.
 *
 * Nothing in the database says who is playing - `LoginServer.cs` is a plain
 * in-memory dictionary - so the gate asks four independent questions and lets
 * any one of them refuse. They are chosen to cover each other's blind spots:
 *
 *   presence      sockets, including a player sitting at character select
 *                 (who is never periodically saved). Blind to offline players
 *                 and to anyone bypassing the proxy.
 *   writeRecency  anything in-world, because `PeriodicSaveProgressPlugIn`
 *                 saves every in-world player once a minute. This is what
 *                 catches OpenMU's offline levelling, which has no socket at
 *                 all. Blind to a live account that changes nothing.
 *   personalStore a character parked with a store open - the idle-but-live
 *                 case the other two miss.
 *   portProbe     whether the game port is reachable from outside. Presence is
 *                 only authoritative while the proxy is the only way in, so
 *                 that gets verified rather than assumed.
 *
 * Every signal fails closed. An error, an unreachable service and a missing
 * configuration all read as "refuse", never as "safe". The one reading that
 * looks like an exception - the port probe's timeout - is argued at `tcpProbe`.
 */

export type SignalName = 'presence' | 'writeRecency' | 'personalStore' | 'portProbe';

export interface SignalResult {
  name: SignalName;
  safe: boolean;
  /** Always populated, including when safe, so the audit log records what was seen. */
  reason: string;
  detail?: Record<string, unknown>;
}

export interface GateVerdict {
  account: string;
  safe: boolean;
  /** Why not. Empty when safe. */
  refusals: string[];
  signals: SignalResult[];
  checkedAt: number;
}

export interface GateConfig {
  presenceUrl: string;
  /** How long after the last socket closed before a write is allowed. */
  offlineCooldownMs: number;
  /** `PeriodicSaveProgressPlugIn`'s interval. Its default is one minute. */
  saveIntervalMs: number;
  /** Margin on top of two save intervals before recent writes stop counting. */
  recencyMarginMs: number;
  /** The public address of the game server, as a player's .exe would dial it. */
  gameHost: string | null;
  gamePort: number | null;
  probeTimeoutMs: number;
  probeCacheMs: number;
  requestTimeoutMs: number;
}

export function loadGateConfig(env: Record<string, string | undefined> = process.env): GateConfig {
  const port = Number(env.GAME_PROBE_PORT ?? 0);

  return {
    presenceUrl: env.PRESENCE_URL ?? 'http://127.0.0.1:3001',
    offlineCooldownMs: Number(env.OFFLINE_COOLDOWN_MS ?? 60_000),
    saveIntervalMs: Number(env.SAVE_INTERVAL_MS ?? 60_000),
    recencyMarginMs: Number(env.RECENCY_MARGIN_MS ?? 60_000),
    gameHost: env.GAME_PROBE_HOST ?? null,
    gamePort: port > 0 && port <= 65535 ? port : null,
    probeTimeoutMs: Number(env.GAME_PROBE_TIMEOUT_MS ?? 3_000),
    probeCacheMs: Number(env.GAME_PROBE_CACHE_MS ?? 60_000),
    requestTimeoutMs: Number(env.GATE_REQUEST_TIMEOUT_MS ?? 5_000),
  };
}

/* ------------------------------------------------------------------- schema */

/**
 * OpenMU's tables are generated by EF Core, so the column names are convention
 * rather than something this repo can read off a model. Two are confirmed
 * (`Item."DefinitionId"` in `Item.Generated.cs`, `Account."VaultId"` by the
 * register service's INSERT); the rest follow the same `<Navigation>Id` rule,
 * and the many-to-many join between an item definition and its option
 * definitions follows EF's `<Owner><Target>` rule, which is why that one
 * carries alternatives.
 *
 * Rather than hardcode the guess, the gate resolves them from
 * `information_schema` on first use and says exactly what is missing when the
 * database disagrees - which is far easier to act on than a syntax error deep
 * inside a query.
 *
 * Every table the shop will ever name is listed here, the fulfilment
 * transaction's included, although the gate itself reads only the first
 * three. One registry and one resolver means `bun run cashshop-gate --schema`
 * shows exactly what the worker will use, and there is no second identifier
 * whitelist to relax by accident.
 */
export interface TableSpec {
  schema: string;
  /** One name, or candidates best first. */
  table: string | string[];
  /** logical name -> the column names that would satisfy it, best first. */
  columns: Record<string, string[]>;
}

const TABLES = {
  account: {
    schema: 'data',
    table: 'Account',
    columns: {
      id: ['Id'],
      loginName: ['LoginName'],
      state: ['State'],
      vault: ['VaultId'],
    },
  },
  character: {
    schema: 'data',
    table: 'Character',
    columns: {
      id: ['Id'],
      name: ['Name'],
      account: ['AccountId'],
      inventory: ['InventoryId'],
      slot: ['CharacterSlot'],
      storeOpened: ['IsStoreOpened'],
      inventoryExtensions: ['InventoryExtensions'],
    },
  },
  item: {
    schema: 'data',
    table: 'Item',
    columns: {
      id: ['Id'],
      storage: ['ItemStorageId'],
      definition: ['DefinitionId'],
      slot: ['ItemSlot'],
      durability: ['Durability'],
      level: ['Level'],
      hasSkill: ['HasSkill'],
      socketCount: ['SocketCount'],
      petExperience: ['PetExperience'],
    },
  },
  itemOptionLink: {
    schema: 'data',
    table: 'ItemOptionLink',
    columns: {
      id: ['Id'],
      item: ['ItemId'],
      option: ['ItemOptionId'],
      level: ['Level'],
      index: ['Index'],
    },
  },
  itemDefinition: {
    schema: 'config',
    table: 'ItemDefinition',
    columns: {
      id: ['Id'],
      configuration: ['GameConfigurationId'],
      group: ['Group'],
      number: ['Number'],
      name: ['Name'],
      width: ['Width'],
      height: ['Height'],
      durability: ['Durability'],
      maximumLevel: ['MaximumItemLevel'],
    },
  },
  /** `ItemDefinition.PossibleItemOptions`, a many-to-many. */
  definitionOptions: {
    schema: 'config',
    table: ['ItemDefinitionItemOptionDefinition', 'ItemOptionDefinitionItemDefinition'],
    columns: {
      definition: ['ItemDefinitionId'],
      optionDefinition: ['ItemOptionDefinitionId', 'PossibleItemOptionsId'],
    },
  },
  /** `ItemOptionDefinition.PossibleOptions`, one-to-many, so the option carries the key. */
  increasableOption: {
    schema: 'config',
    table: 'IncreasableItemOption',
    columns: {
      id: ['Id'],
      number: ['Number'],
      type: ['OptionTypeId'],
      optionDefinition: ['ItemOptionDefinitionId'],
    },
  },
  itemOptionType: {
    schema: 'config',
    table: 'ItemOptionType',
    columns: { id: ['Id'], name: ['Name'] },
  },
  gameConfiguration: {
    schema: 'config',
    table: 'GameConfiguration',
    columns: { id: ['Id'] },
  },
  gameServerDefinition: {
    schema: 'config',
    table: 'GameServerDefinition',
    columns: { id: ['Id'], configuration: ['GameConfigurationId'] },
  },
} satisfies Record<string, TableSpec>;

export type TableName = keyof typeof TABLES;

type Columns<K extends TableName> = Record<keyof (typeof TABLES)[K]['columns'], string>;

export interface ResolvedTable<K extends TableName = TableName> {
  schema: string;
  table: string;
  /** Ready to interpolate: `"schema"."Table"`. */
  ref: string;
  /** logical name -> the column as the database names it, for printing. */
  columns: Columns<K>;
  /** logical name -> that column quoted, ready to interpolate. */
  col: Columns<K>;
  /** NOT NULL columns with no default: everything an INSERT must supply. */
  required: Set<string>;
}

export type ResolvedSchema = { [K in TableName]: ResolvedTable<K> };

/** Identifiers are interpolated into SQL, so nothing exotic may pass. */
const IDENTIFIER_RE = /^[A-Za-z][A-Za-z0-9_]*$/;

export function quote(name: string): string {
  if (!IDENTIFIER_RE.test(name)) {
    throw new Error(`refusing to use "${name}" as a SQL identifier`);
  }
  return `"${name}"`;
}

interface ColumnRow {
  table_schema: string;
  table_name: string;
  column_name: string;
  is_nullable: 'YES' | 'NO';
  column_default: string | null;
}

function candidatesOf(spec: TableSpec): string[] {
  return Array.isArray(spec.table) ? spec.table : [spec.table];
}

export async function resolveSchema(sql: Sql): Promise<ResolvedSchema> {
  const specs = Object.values(TABLES) as TableSpec[];
  const wanted = specs.flatMap(spec =>
    candidatesOf(spec).map(table => [spec.schema, table] as [string, string])
  );
  const rows = await sql<ColumnRow[]>`
    SELECT table_schema, table_name, column_name, is_nullable, column_default
    FROM information_schema.columns
    WHERE (table_schema, table_name) IN ${sql(wanted)}
  `;

  const present = new Map<string, ColumnRow[]>();
  for (const row of rows) {
    const key = `${row.table_schema}.${row.table_name}`;
    present.set(key, [...(present.get(key) ?? []), row]);
  }

  const resolved: Partial<Record<TableName, ResolvedTable>> = {};
  const missing: string[] = [];

  for (const [logicalTable, spec] of Object.entries(TABLES) as [TableName, TableSpec][]) {
    const candidates = candidatesOf(spec);
    const table = candidates.find(candidate => present.has(`${spec.schema}.${candidate}`));

    if (!table) {
      missing.push(`no table ${spec.schema}.${candidates.join(' or ')}`);
      continue;
    }

    const key = `${spec.schema}.${table}`;
    const columns = present.get(key) ?? [];
    const names = new Set(columns.map(column => column.column_name));
    const picked: Record<string, string> = {};
    const col: Record<string, string> = {};

    for (const [logicalColumn, options] of Object.entries(spec.columns)) {
      const found = options.find(candidate => names.has(candidate));

      if (found) {
        picked[logicalColumn] = found;
        col[logicalColumn] = quote(found);
      } else {
        missing.push(
          `${key} has no column for ${logicalColumn} (looked for ${options.join(', ')}; ` +
            `it has ${[...names].sort().join(', ')})`
        );
      }
    }

    resolved[logicalTable] = {
      schema: spec.schema,
      table,
      ref: `${quote(spec.schema)}.${quote(table)}`,
      columns: picked,
      col,
      required: new Set(
        columns
          .filter(column => column.is_nullable === 'NO' && column.column_default === null)
          .map(column => column.column_name)
      ),
    };
  }

  if (missing.length) {
    throw new Error(`OpenMU schema does not look as expected:\n  ${missing.join('\n  ')}`);
  }

  return resolved as ResolvedSchema;
}

/* -------------------------------------------------------------------- gate */

export interface AccountRow {
  id: string;
  loginName: string;
  state: number;
  vaultId: string | null;
}

interface PresenceAnswer {
  online: boolean;
  connections: number;
  lastSeenAt: number | null;
  startedAt: number;
  now: number;
  unidentifiedConnections: number;
}

interface RecencySample {
  fingerprint: string;
  takenAt: number;
}

export class SafetyGate {
  private schema: ResolvedSchema | null = null;
  private probe: { at: number; outcome: ProbeOutcome; detail: string } | null = null;
  /** Only used when `track_commit_timestamp` is off. account id -> last sample. */
  private readonly samples = new Map<string, RecencySample>();
  private commitTimestamps: boolean | null = null;

  constructor(
    private readonly sql: Sql,
    private readonly config: GateConfig = loadGateConfig()
  ) {}

  /** How long a write must be absent before it stops meaning "someone is playing". */
  private get recencyWindowMs(): number {
    return this.config.saveIntervalMs * 2 + this.config.recencyMarginMs;
  }

  async schemaOnce(): Promise<ResolvedSchema> {
    return (this.schema ??= await resolveSchema(this.sql));
  }

  async findAccount(loginName: string): Promise<AccountRow | null> {
    const a = (await this.schemaOnce()).account;
    const rows = await this.sql.unsafe<AccountRow[]>(
      `SELECT ${a.col.id} AS id, ${a.col.loginName} AS "loginName",
              ${a.col.state} AS state, ${a.col.vault} AS "vaultId"
         FROM ${a.ref}
        WHERE lower(${a.col.loginName}) = lower($1)
        LIMIT 1`,
      [loginName]
    );

    return rows[0] ?? null;
  }

  /**
   * The verdict for one account. Signals run together - three of the four are
   * independent - and every one of them is reported, safe or not, so the audit
   * log can record the whole picture rather than the first refusal.
   */
  async check(loginName: string): Promise<GateVerdict> {
    const checkedAt = Date.now();

    let account: AccountRow | null = null;
    let lookupError: string | null = null;

    try {
      account = await this.findAccount(loginName);
    } catch (error) {
      lookupError = describe(error);
    }

    const dbSignals: Promise<SignalResult[]> =
      lookupError !== null
        ? Promise.resolve([
            refuse('writeRecency', `account lookup failed: ${lookupError}`),
            refuse('personalStore', `account lookup failed: ${lookupError}`),
          ])
        : account === null
          ? Promise.resolve([
              refuse('writeRecency', `no account named ${loginName}`),
              refuse('personalStore', `no account named ${loginName}`),
            ])
          : Promise.all([this.writeRecency(account), this.personalStore(account)]);

    const [presence, [writeRecency, personalStore], portProbe] = await Promise.all([
      this.presence(loginName),
      dbSignals,
      this.portProbe(),
    ]);

    const signals = [presence, writeRecency, personalStore, portProbe];
    const refusals = signals.filter(signal => !signal.safe).map(signal => `${signal.name}: ${signal.reason}`);

    return { account: loginName, safe: refusals.length === 0, refusals, signals, checkedAt };
  }

  /* ---------------------------------------------------------- signal: sockets */

  private async presence(loginName: string): Promise<SignalResult> {
    let answer: PresenceAnswer;

    try {
      const response = await fetch(
        `${this.config.presenceUrl}/presence/${encodeURIComponent(loginName)}`,
        { signal: AbortSignal.timeout(this.config.requestTimeoutMs) }
      );

      if (!response.ok) {
        return refuse('presence', `presence service answered HTTP ${response.status}`);
      }

      answer = (await response.json()) as PresenceAnswer;
    } catch (error) {
      // The proxy being down does not mean nobody is playing - it means we
      // cannot tell, and the whole point of the gate is not to guess.
      return refuse('presence', `presence service unreachable: ${describe(error)}`);
    }

    const detail = {
      connections: answer.connections,
      lastSeenAt: answer.lastSeenAt,
      unidentifiedConnections: answer.unidentifiedConnections,
    };

    if (answer.unidentifiedConnections > 0) {
      return refuse(
        'presence',
        `${answer.unidentifiedConnections} open socket(s) could not be identified, so any of them could be this account`,
        detail
      );
    }

    if (answer.online) {
      return refuse('presence', `logged in on ${answer.connections} connection(s)`, detail);
    }

    // A session this proxy never witnessed died with the previous process, and
    // the game server needs a moment to notice and finish saving - so its
    // start counts as a sighting for the length of the cooldown.
    const since = Math.max(answer.lastSeenAt ?? 0, answer.startedAt);
    const quiet = answer.now - since;

    if (quiet < this.config.offlineCooldownMs) {
      return refuse(
        'presence',
        `logged out ${Math.round(quiet / 1000)}s ago, waiting ${Math.round(this.config.offlineCooldownMs / 1000)}s`,
        detail
      );
    }

    return allow('presence', `no socket for ${Math.round(quiet / 1000)}s`, detail);
  }

  /* ----------------------------------------------------- signal: write recency */

  private async writeRecency(account: AccountRow): Promise<SignalResult> {
    try {
      if (this.commitTimestamps === null) {
        const [row] = await this.sql<{ setting: string }[]>`SHOW track_commit_timestamp`;
        this.commitTimestamps = row?.setting === 'on';
      }

      return this.commitTimestamps
        ? await this.recencyByCommitTimestamp(account)
        : await this.recencyBySampling(account);
    } catch (error) {
      return refuse('writeRecency', `could not read write recency: ${describe(error)}`);
    }
  }

  /** The direct answer, when Postgres is keeping commit timestamps. */
  private async recencyByCommitTimestamp(account: AccountRow): Promise<SignalResult> {
    const rows = await this.sql.unsafe<{ last_write: Date | null }[]>(
      `SELECT max(pg_xact_commit_timestamp(t.xmin)) AS last_write FROM (${this.rowsOfAccountSql()}) t`,
      [account.id]
    );

    const lastWrite = rows[0]?.last_write ?? null;

    if (lastWrite === null) {
      return allow('writeRecency', 'no character or item rows to have been written');
    }

    const age = Date.now() - lastWrite.getTime();
    const detail = { lastWrite: lastWrite.toISOString(), ageMs: age, windowMs: this.recencyWindowMs };

    return age < this.recencyWindowMs
      ? refuse(
          'writeRecency',
          `written ${Math.round(age / 1000)}s ago, which is inside the ${Math.round(this.recencyWindowMs / 1000)}s window`,
          detail
        )
      : allow('writeRecency', `last written ${Math.round(age / 1000)}s ago`, detail);
  }

  /**
   * The fallback when `track_commit_timestamp` is off: compare the rows'
   * transaction ids across two samples more than one save interval apart. An
   * in-world player is saved every minute, so anything that changed between
   * the samples is being played.
   *
   * The first call can only ever answer "not yet" - it has nothing to compare
   * against. That is the cost of not enabling the setting.
   */
  private async recencyBySampling(account: AccountRow): Promise<SignalResult> {
    const rows = await this.sql.unsafe<{ fingerprint: string | null }[]>(
      `SELECT md5(string_agg(t.xmin::text, ',' ORDER BY t.xmin::text)) AS fingerprint
         FROM (${this.rowsOfAccountSql()}) t`,
      [account.id]
    );

    const fingerprint = rows[0]?.fingerprint ?? 'empty';
    const now = Date.now();
    const previous = this.samples.get(account.id);
    const needed = this.config.saveIntervalMs + this.config.recencyMarginMs;

    if (!previous) {
      this.samples.set(account.id, { fingerprint, takenAt: now });
      return refuse(
        'writeRecency',
        `track_commit_timestamp is off, so this needs a second sample in ${Math.round(needed / 1000)}s`,
        { fingerprint, sampled: 1 }
      );
    }

    if (previous.fingerprint !== fingerprint) {
      this.samples.set(account.id, { fingerprint, takenAt: now });
      return refuse('writeRecency', 'rows changed since the last sample, so someone is playing', {
        fingerprint,
        sampled: 2,
      });
    }

    const held = now - previous.takenAt;

    if (held < needed) {
      return refuse(
        'writeRecency',
        `unchanged for only ${Math.round(held / 1000)}s, need ${Math.round(needed / 1000)}s`,
        { fingerprint, heldMs: held }
      );
    }

    return allow('writeRecency', `unchanged for ${Math.round(held / 1000)}s`, {
      fingerprint,
      heldMs: held,
    });
  }

  /**
   * Every character row of the account, plus every item in those characters'
   * inventories and in the account vault. `$1` is the account id.
   */
  private rowsOfAccountSql(): string {
    if (!this.schema) throw new Error('schema not resolved');

    const { account: a, character: c, item: i } = this.schema;

    return `
      SELECT c.xmin FROM ${c.ref} c WHERE c.${c.col.account} = $1
      UNION ALL
      SELECT i.xmin FROM ${i.ref} i
       WHERE i.${i.col.storage} IN (
         SELECT c2.${c.col.inventory} FROM ${c.ref} c2 WHERE c2.${c.col.account} = $1
         UNION ALL
         SELECT a.${a.col.vault} FROM ${a.ref} a WHERE a.${a.col.id} = $1
       )`;
  }

  /* ---------------------------------------------------- signal: personal store */

  private async personalStore(account: AccountRow): Promise<SignalResult> {
    try {
      const { character: c } = await this.schemaOnce();
      const rows = await this.sql.unsafe<{ name: string }[]>(
        `SELECT ${c.col.name} AS name
           FROM ${c.ref}
          WHERE ${c.col.account} = $1 AND ${c.col.storeOpened} = true`,
        [account.id]
      );

      return rows.length
        ? refuse('personalStore', `store open on ${rows.map(row => row.name).join(', ')}`, {
            characters: rows.map(row => row.name),
          })
        : allow('personalStore', 'no character has a store open');
    } catch (error) {
      return refuse('personalStore', `could not read store flags: ${describe(error)}`);
    }
  }

  /* --------------------------------------------------------- signal: port probe */

  /**
   * Socket presence is only worth anything while the proxy is the only way in.
   * If the game port answers from its public address, a player on the original
   * client can play without the proxy ever seeing them - so the shop stops
   * writing entirely rather than trusting a signal it knows is bypassable.
   */
  private async portProbe(): Promise<SignalResult> {
    const { gameHost, gamePort } = this.config;

    if (!gameHost || !gamePort) {
      return refuse(
        'portProbe',
        'GAME_PROBE_HOST / GAME_PROBE_PORT are not set, so the proxy cannot be shown to be the only way in'
      );
    }

    const target = `${gameHost}:${gamePort}`;
    const now = Date.now();
    let probe = this.probe;

    if (!probe || now - probe.at >= this.config.probeCacheMs) {
      probe = { at: now, ...(await tcpProbe(gameHost, gamePort, this.config.probeTimeoutMs)) };
      this.probe = probe;
    }

    const detail = `${probe.at === now ? '' : '(cached) '}${probe.detail}`;
    const seen = { target, probedAt: probe.at };

    if (probe.outcome === 'open') {
      return refuse('portProbe', `${target} is reachable from outside: ${detail}`, seen);
    }

    if (probe.outcome === 'inconclusive') {
      return refuse('portProbe', `${target} could not be probed: ${detail}`, seen);
    }

    return allow('portProbe', `${target} is closed to the outside: ${detail}`, seen);
  }
}

/* ------------------------------------------------------------------ helpers */

function allow(name: SignalName, reason: string, detail?: Record<string, unknown>): SignalResult {
  return { name, safe: true, reason, detail };
}

function refuse(name: SignalName, reason: string, detail?: Record<string, unknown>): SignalResult {
  return { name, safe: false, reason, detail };
}

function describe(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export type ProbeOutcome = 'open' | 'closed' | 'inconclusive';

/**
 * Dials the port once. Three answers, and only two of them say anything
 * about the port:
 *
 *   open          the handshake completed: something is listening.
 *   closed        the SYN was answered with a reset (ECONNREFUSED: nothing
 *                 listens, or the firewall REJECTs), or nobody answered it at
 *                 all within the timeout.
 *   inconclusive  anything else - a name that does not resolve, no route, a
 *                 permission or descriptor limit. The probe never reached the
 *                 network at the address it was asked about, so it proves
 *                 nothing, and the gate refuses. A typo in `GAME_PROBE_HOST`
 *                 is the likeliest way here, and it must not read as "closed".
 *
 * Silence is `closed`, and that needs arguing next to "fail closed". The
 * probe exists to show the game port unreachable from where a player's client
 * would dial it, and the ordinary way an operator makes a port unreachable -
 * a cloud security group, `iptables -P INPUT DROP`, ufw - is to drop the SYN,
 * which from the dialling side is silence until the timer runs out. A reset
 * is the rarer posture. Were silence inconclusive, the common deployment
 * would never deliver anything, and the only way an operator could then get
 * a delivery is to point `GAME_PROBE_HOST` at something that resets, which
 * would trade an honest reading for a rigged one. Silence is trusted because
 * what else it could mean is ruled out: a host with no route fails at once
 * (ENETUNREACH, EHOSTUNREACH), a name that does not resolve fails at once
 * (ENOTFOUND), and both are `inconclusive`. What silence cannot rule out is a
 * probe run from somewhere the firewall treats differently from the internet
 * - the game box behind a NAT that does not hairpin its own public address -
 * which is why the address is the one a player dials and the probe has to
 * run from a host whose path to it is the internet's.
 *
 * `node:net` rather than `Bun.connect`, because Bun reports every failure to
 * connect as ECONNREFUSED, an unresolvable name and an unroutable address
 * included, and that would make the typo above read as a closed port. Node's
 * socket keeps the real code.
 */
export function tcpProbe(
  host: string,
  port: number,
  timeoutMs: number
): Promise<{ outcome: ProbeOutcome; detail: string }> {
  return new Promise(resolve => {
    const socket = net.connect({ host, port });
    let settled = false;

    const finish = (outcome: ProbeOutcome, detail: string) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      socket.destroy();
      resolve({ outcome, detail });
    };

    const timer = setTimeout(() => finish('closed', `no answer in ${timeoutMs}ms`), timeoutMs);

    socket.once('connect', () => finish('open', 'connected'));
    socket.once('error', (error: NodeJS.ErrnoException) => {
      if (error.code === 'ECONNREFUSED') {
        finish('closed', 'connection refused');
      } else {
        finish('inconclusive', `${error.code ?? 'error'}: ${describe(error)}`);
      }
    });
  });
}
