/**
 * Writes `configuration_hex.md` from the options that actually exist.
 *
 * The table is generated rather than hand-kept so it cannot drift from the
 * client: `src/common/configFingerprint.test.ts` regenerates it and fails if
 * the committed file differs, which is what makes an old screenshot still
 * decodable years later.
 *
 *   bun run tools/configHexTable.ts
 */
import { writeFileSync } from 'fs';
import {
  CONFIG_FINGERPRINT_VERSION,
  NUMBER_BIAS,
  flagFields,
  numberFields,
} from '../src/common/configFingerprint';

export function configHexTable(): string {
  const flags = flagFields();
  const numbers = numberFields();
  const flagBytes = Math.ceil(flags.length / 8);

  const lines: string[] = [];

  lines.push('# Configuration hex');
  lines.push('');
  lines.push(
    'The `config` row of the performance overlay (Shift+Ctrl+Alt+P) is every'
  );
  lines.push(
    'setting the player has, packed into hex, so a screenshot of a report'
  );
  lines.push('carries the configuration that produced it. This is how to read it.');
  lines.push('');
  lines.push(
    'Generated by `tools/configHexTable.ts`; do not edit by hand. A test'
  );
  lines.push('regenerates it and fails if this file no longer matches the client.');
  lines.push('');
  lines.push(`Format version: **${CONFIG_FINGERPRINT_VERSION}**`);
  lines.push('');
  lines.push('## Layout');
  lines.push('');
  lines.push('| Offset | Bytes | What |');
  lines.push('|---|---|---|');
  lines.push('| 0 | 1 | Format version. Anything else means a different table. |');
  lines.push(`| 1 | 1 | Number of flag bytes that follow (currently ${flagBytes}). |`);
  lines.push(
    `| 2 | ${flagBytes} | The on/off settings, one bit each, first in bit 0 of the first byte. |`
  );
  lines.push(
    `| ${2 + flagBytes} | 1 | Number of value bytes that follow (currently ${numbers.length}). |`
  );
  lines.push(
    `| ${3 + flagBytes} | ${numbers.length} | The numeric settings, one byte each, each stored as value + ${NUMBER_BIAS}. |`
  );
  lines.push(
    `| ${3 + flagBytes + numbers.length} | 2 | Language, two ASCII letters (\`65 73\` is \`es\`). |`
  );
  lines.push(
    `| ${5 + flagBytes + numbers.length} | 2 | Texture pack digest, \`0000\` when the original textures are in use. |`
  );
  lines.push('');
  lines.push(
    `Total: **${5 + flagBytes + numbers.length + 2} bytes**, ${(5 + flagBytes + numbers.length + 2) * 2} hex characters.`
  );
  lines.push('');
  lines.push('## On/off settings');
  lines.push('');
  lines.push(
    'Bit `n` counts from the first flag byte: byte `n / 8`, bit `n % 8`, lowest bit first.'
  );
  lines.push('');
  lines.push('| Bit | Byte.bit | Setting |');
  lines.push('|---|---|---|');
  flags.forEach((name, i) => {
    lines.push(`| ${i} | ${i >> 3}.${i & 7} | \`${name}\` |`);
  });
  lines.push('');
  lines.push('## Value settings');
  lines.push('');
  lines.push(
    `Each is one byte; subtract ${NUMBER_BIAS} to get the value. Index 0 is the first byte after the count.`
  );
  lines.push('');
  lines.push('| Index | Setting |');
  lines.push('|---|---|');
  numbers.forEach((name, i) => {
    lines.push(`| ${i} | \`${name}\` |`);
  });
  lines.push('');
  lines.push('## Worked example');
  lines.push('');
  lines.push('```');
  lines.push('01 07 ff 7b ... 4a 80 81 ... 65 73 0000');
  lines.push('```');
  lines.push('');
  lines.push(
    '`01` version 1, `07` seven flag bytes, then the flags, then the count of'
  );
  lines.push(
    'value bytes and the values (`80` is 0, `81` is 1, `7f` is -1), then `65 73`'
  );
  lines.push('for Spanish and `0000` for no texture pack.');
  lines.push('');

  return lines.join('\n');
}

if (import.meta.main) {
  const out = new URL('../configuration_hex.md', import.meta.url).pathname;
  writeFileSync(out.replace(/^\/([A-Za-z]:)/, '$1'), configHexTable());
  console.log('wrote configuration_hex.md');
}
