/**
 * Builds `src/common/itemIconFit.ts` from the pixels in `public/items`.
 *
 *   bun run tools/itemIconFit.ts
 *
 * The pack renders every item at one world scale into a canvas sized by the
 * item's inventory footprint, so a small item covers a small part of its own
 * PNG - a jewel is 21 x 25 opaque pixels inside 120 x 126. Fitting that whole
 * canvas into the square leaves a few pixels of jewel, which is why small
 * items were unreadable. Measuring the opaque box once, here, lets the icon
 * be zoomed to its square at runtime with no per-frame cost.
 *
 * Re-run whenever files are added to or removed from `public/items`.
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { PNG } from 'pngjs';

const ROOT = join(import.meta.dir, '..');
const ITEMS_DIR = join(ROOT, 'public', 'items');
const OUT = join(ROOT, 'src', 'common', 'itemIconFit.ts');

const FILE = /^item_(\d+)_(\d+)_(\d+)(_e|_a)?\.png$/;

/** Below this the pixel is the render's own anti-aliased fringe, not the item. */
const ALPHA_FLOOR = 8;
/** Leaves the item off the square's border. */
const MARGIN = 0.9;
/** A near-empty render must not blow up to fill the square. */
const MAX_ZOOM = 6;
/** Under this the zoom is not worth an entry. */
const MIN_ZOOM = 1.05;

type Box = { zoom: number; dx: number; dy: number };

function measure(file: string): Box | null {
  const png = PNG.sync.read(readFileSync(join(ITEMS_DIR, file)));
  const { width, height, data } = png;

  let x0 = width;
  let y0 = height;
  let x1 = -1;
  let y1 = -1;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (data[(y * width + x) * 4 + 3] < ALPHA_FLOOR) continue;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }

  if (x1 < 0) return null;

  const w = x1 - x0 + 1;
  const h = y1 - y0 + 1;

  return {
    zoom: Math.min(width / w, height / h, MAX_ZOOM / MARGIN) * MARGIN,
    // The content is drawn centred, but only roughly; the zoom is about the
    // canvas centre, so the drift has to come off first or it scales too.
    dx: 0.5 - (x0 + x1 + 1) / 2 / width,
    dy: 0.5 - (y0 + y1 + 1) / 2 / height,
  };
}

/** The plain tints first: the `_e` aura would measure wider than the item. */
const RANK = (name: string) => (name.includes('_e.') ? 2 : name.includes('_a.') ? 1 : 0);

const candidates = new Map<string, string>();

for (const name of readdirSync(ITEMS_DIR)) {
  const m = FILE.exec(name);
  if (!m) continue;
  const key = `${m[1]}_${m[2]}`;
  const held = candidates.get(key);
  if (!held || RANK(name) < RANK(held)) candidates.set(key, name);
}

const fits = new Map<string, Box>();
let empty = 0;

for (const [key, file] of candidates) {
  const box = measure(file);
  if (!box) {
    empty++;
    continue;
  }
  if (box.zoom < MIN_ZOOM) continue;
  fits.set(key, box);
}

const keys = [...fits.keys()].sort((a, b) => {
  const [ga, na] = a.split('_').map(Number);
  const [gb, nb] = b.split('_').map(Number);
  return ga - gb || na - nb;
});

const round = (n: number, places: number) => Number(n.toFixed(places));

const lines = keys.map(key => {
  const box = fits.get(key)!;
  return `  '${key}': [${round(box.zoom, 2)}, ${round(box.dx, 3)}, ${round(box.dy, 3)}],`;
});

const source = `// GENERATED by tools/itemIconFit.ts - do not edit.
// ${keys.length} of ${candidates.size} items measured${empty ? `, ${empty} blank` : ''}.
//
// \`group_num\` → [zoom, dx, dy]: how far the icon has to be blown up for its
// opaque pixels to fill the square, and the drift off centre that has to come
// off first. Consumed by ui/components/itemIcon.
export const ITEM_ICON_FIT: Readonly<Record<string, readonly [number, number, number]>> = {
${lines.join('\n')}
};
`;

writeFileSync(OUT, source);
console.log(`wrote ${OUT}: ${keys.length} items`);
