/**
 * Builds `src/common/itemIconManifest.ts` from what is actually in
 * `public/items`: one bitmask per `group_num` saying which tint / excellent
 * variants exist, so `itemIconPackChain` never asks the server for a file
 * that is not there (the pack is uneven — see itemIconPack.ts).
 *
 *   bun run tools/itemIconManifest.ts
 *
 * Re-run whenever files are added to or removed from `public/items`.
 */
import { readdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const ITEMS_DIR = join(ROOT, 'public', 'items');
const OUT = join(ROOT, 'src', 'common', 'itemIconManifest.ts');

/** Same order as `ITEM_ICON_TINTS` in itemIconPack.ts. */
const TINTS = [0, 3, 5, 7, 9, 11, 13, 15];

const FILE = /^item_(\d+)_(\d+)_(\d+)(_e|_a)?\.png$/;

const masks = new Map<string, number>();
let files = 0;
let skipped = 0;

for (const name of readdirSync(ITEMS_DIR)) {
  const m = FILE.exec(name);
  if (!m) continue;
  const tint = TINTS.indexOf(Number(m[3]));
  if (tint < 0) {
    skipped++;
    continue;
  }
  const key = `${m[1]}_${m[2]}`;
  const variant = m[4] === "_e" ? 1 : m[4] === "_a" ? 2 : 0;
  const bit = 1 << (tint + variant * TINTS.length);
  masks.set(key, (masks.get(key) ?? 0) | bit);
  files++;
}

const keys = [...masks.keys()].sort((a, b) => {
  const [ga, na] = a.split('_').map(Number);
  const [gb, nb] = b.split('_').map(Number);
  return ga - gb || na - nb;
});

const lines = keys.map(key => `  '${key}': ${masks.get(key)},`);

const source = `// GENERATED by tools/itemIconManifest.ts — do not edit.
// ${files} files in public/items over ${keys.length} items.
//
// \`group_num\` → bitmask of the pack files that exist: bit i = tint
// ITEM_ICON_TINTS[i] exists, bit 8 + i = the excellent (\`_e\`) variant of
// that tint, bit 16 + i = the ancient (\`_a\`) variant. Consumed by itemIconPack.ts.
export const ITEM_ICON_MANIFEST: Readonly<Record<string, number>> = {
${lines.join('\n')}
};
`;

writeFileSync(OUT, source);
console.log(
  `wrote ${OUT}: ${keys.length} items, ${files} files` +
    (skipped ? `, ${skipped} skipped (unknown tint)` : '')
);
